Xamarin.PropertyEditing.Windows/EditorPropertySelector.cs
Xamarin.PropertyEditing.Windows/PointEditorControl.cs
Xamarin.PropertyEditing.Windows/PropertyEditorPanel.cs
Xamarin.PropertyEditing.Windows/Resources.xaml
Xamarin.PropertyEditing.Windows/SizeEditorControl.cs
Xamarin.PropertyEditing.Windows/ThicknessEditorControl.cs
Xamarin.PropertyEditing.Windows/Xamarin.PropertyEditing.Windows.csproj

In the image below the editors are seen on RenderTransformOrigin, RenderSize & Padding... properties

[Windows]Add Point, Size and Thickness Editors.

---

Xamarin.PropertyEditing.Windows/NumericUpDownControl.cs
Xamarin.PropertyEditing.Windows/PropertyEditorControl.cs
Xamarin.PropertyEditing.Windows/Resources.xaml

- Adds narrator support for a number of controls
- Improves keyboard navigation

Windows accessibility improvements

---

Xamarin.PropertyEditing.Tests/ConstrainedPropertyViewModelTests.cs
Xamarin.PropertyEditing.Windows/PropertyEditorPanel.cs
Xamarin.PropertyEditing.Windows/Resources.xaml
Xamarin.PropertyEditing.Windows/Themes/PropertyEditorPanelStyle.xaml
Xamarin.PropertyEditing.Windows/Themes/VS.Light.xaml
Xamarin.PropertyEditing/ObservableLookup.cs
Xamarin.PropertyEditing/ViewModels/PropertiesViewModel.cs

This fixes the grouping under name arrangement, removes irrelevant tests, adds  panel color and improves a performance issue.

Improve Windows look & feel

---

Xamarin.PropertyEditing.Mac/Controls/CGRectEditorControl.cs
Xamarin.PropertyEditing.Mac/Controls/PropertyEditorControl.cs
Xamarin.PropertyEditing.Mac/PropertyEditorPanel.cs
Xamarin.PropertyEditing.Mac/PropertyTableDelegate.cs

By creating the editors in the RowHeight we can get the editor's height straight away. If the editor is already created, event better.

Added RowHeight support and refactored CGRect to be multi-line.

---

Xamarin.PropertyEditing.Mac/Controls/BasePointEditorControl.cs
Xamarin.PropertyEditing.Mac/Controls/CGPointEditorControl.cs
Xamarin.PropertyEditing.Mac/Controls/CGSizeEditorControl.cs
Xamarin.PropertyEditing.Mac/PropertyEditorPanel.cs
Xamarin.PropertyEditing.Mac/PropertyTableDelegate.cs
Xamarin.PropertyEditing.Mac/Xamarin.PropertyEditing.Mac.csproj

Refactor to support multiple 2 point objects.

Generic point editor control

---

Xamarin.PropertyEditing.Windows/Themes/MenuButtonStyle.xaml
Xamarin.PropertyEditing.Windows/Themes/PropertyEditorPanelStyle.xaml
Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
Xamarin.PropertyEditing.Windows/Themes/VS.Dark.xaml
Xamarin.PropertyEditing.Windows/Themes/VS.Light.xaml

Dark theme base elements + VS brush naming

---

Xamarin.PropertyEditing.Tests/EventViewModelTests.cs
Xamarin.PropertyEditing.Tests/MockObjectEditor.cs
Xamarin.PropertyEditing.Tests/PropertiesViewModelTests.cs
Xamarin.PropertyEditing.Tests/Xamarin.PropertyEditing.Tests.csproj
Xamarin.PropertyEditing.Windows/ChoiceControl.cs
Xamarin.PropertyEditing.Windows/PropertyEditorPanel.cs
Xamarin.PropertyEditing.Windows/Themes/PropertyEditorPanelStyle.xaml
Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
Xamarin.PropertyEditing.Windows/Themes/VS.Dark.xaml
Xamarin.PropertyEditing.Windows/Themes/VS.Light.xaml
Xamarin.PropertyEditing.Windows/Xamarin.PropertyEditing.Windows.csproj
Xamarin.PropertyEditing/IEventInfo.cs
Xamarin.PropertyEditing/IObjectEventEditor.cs
Xamarin.PropertyEditing/Reflection/ReflectionEventInfo.cs
Xamarin.PropertyEditing/Reflection/ReflectionObjectEditor.cs
Xamarin.PropertyEditing/ViewModels/EditorViewModel.cs
Xamarin.PropertyEditing/ViewModels/EventViewModel.cs
Xamarin.PropertyEditing/ViewModels/PropertiesViewModel.cs
Xamarin.PropertyEditing/ViewModels/PropertyViewModel.cs
Xamarin.PropertyEditing/Xamarin.PropertyEditing.csproj

The toggle control switching to the events pane still needs some theming work, but that control is part of other editors as well.

[Core/Win] Events core and editor

---

Xamarin.PropertyEditing.Mac/PropertyEditorPanel.cs

Move model mapping to static ctor to allow multiple panels

Allow Mac to have multiple property panels per application

---

Xamarin.PropertyEditing.Tests/IGetAndSet.cs
Xamarin.PropertyEditing.Tests/IPropertyConverter.cs
Xamarin.PropertyEditing.Tests/MockControls/MockControl.cs
Xamarin.PropertyEditing.Tests/MockEditorProvider.cs
Xamarin.PropertyEditing.Tests/MockObjectEditor.cs
Xamarin.PropertyEditing.Tests/MockPropertyInfo/MockEnumPropertyInfo.cs
Xamarin.PropertyEditing.Tests/MockPropertyInfo/MockPropertyInfo.cs
Xamarin.PropertyEditing.Tests/MockPropertyProviderTests.cs
Xamarin.PropertyEditing.Tests/PropertyViewModelTests.cs
Xamarin.PropertyEditing.Tests/Xamarin.PropertyEditing.Tests.csproj
Xamarin.PropertyEditing.Windows/HeaderedContextMenu.cs
Xamarin.PropertyEditing.Windows/NumericUpDownControl.cs
Xamarin.PropertyEditing.Windows/PropertyButton.cs
Xamarin.PropertyEditing.Windows/PropertyMenuItemContainerStyleSelector.cs
Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
Xamarin.PropertyEditing.Windows/Themes/VS.Dark.xaml
Xamarin.PropertyEditing.Windows/Themes/VS.Light.xaml
Xamarin.PropertyEditing.Windows/Xamarin.PropertyEditing.Windows.csproj
Xamarin.PropertyEditing/OrderedDictionary.cs
Xamarin.PropertyEditing/Properties/Resources.Designer.cs
Xamarin.PropertyEditing/Properties/Resources.resx
Xamarin.PropertyEditing/ValueSource.cs
Xamarin.PropertyEditing/ViewModels/PropertyViewModel.cs

[Win] Property button

---

Xamarin.PropertyEditing.Mac.Standalone/Main.storyboard
Xamarin.PropertyEditing.Mac/Controls/PredefinedValuesEditor.cs
Xamarin.PropertyEditing.Mac/PropertyEditorPanel.cs
Xamarin.PropertyEditing/ViewModels/PredefinedValuesViewModel.cs

- Resize Arrange By correctly 
- NSPopUpButton instead of NSComboBox for constrained predefined values.
- Add wantsLayer to storyboard to improve theming drawing and performance

Fixes to UI based on feedback 

---

Xamarin.PropertyEditing.Windows/StringEditorControl.cs
Xamarin.PropertyEditing.Windows/Themes/PropertyEditorPanelStyle.xaml
Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
Xamarin.PropertyEditing.Windows/Themes/VS.Dark.xaml
Xamarin.PropertyEditing.Windows/Themes/VS.Light.xaml
Xamarin.PropertyEditing.Windows/ToggleButtonEx.cs
Xamarin.PropertyEditing.Windows/Xamarin.PropertyEditing.Windows.csproj

This PR:
- Correctly themes combo boxes for light and dark
- Fixes labeling for the size editor
- Fixes the text box border highlight to match
- Matches string editor focus behavior

Theme improvements

---

Xamarin.PropertyEditing.Tests/ThicknessPropertyViewModelTests.cs
Xamarin.PropertyEditing.Tests/Xamarin.PropertyEditing.Tests.csproj
Xamarin.PropertyEditing.Windows/EditorPropertySelector.cs
Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
Xamarin.PropertyEditing/ViewModels/PropertiesViewModel.cs
Xamarin.PropertyEditing/ViewModels/ThicknessPropertyViewModel.cs
Xamarin.PropertyEditing/Xamarin.PropertyEditing.csproj

The thickness editor wasn't actually editing the thickness
values, this adds the needed logic.

Add ThicknessPropertyViewModel with change notification

---

Xamarin.PropertyEditing.Windows/Themes/Resources.xaml

[Win] Fix focus visual for combo boxes

---

Xamarin.PropertyEditing.Tests/MockObjectEditor.cs
Xamarin.PropertyEditing.Windows/ResourceSelectorWindow.xaml
Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
Xamarin.PropertyEditing.Windows/Themes/VS.Dark.xaml
Xamarin.PropertyEditing/ViewModels/ResourceSelectorViewModel.cs
Xamarin.PropertyEditing/ViewModels/SimpleCollectionView.cs

[Win] Further resource selector to design

---

Xamarin.PropertyEditing.Windows/EditorPropertySelector.cs
Xamarin.PropertyEditing.Windows/Themes/PropertyEditorPanelStyle.xaml

For some reason integrating into VS makes the dynamic resources not
evaluate, so we'll go with a simpler but similar solution that works.

[Win] Fix editor template selection

---

Xamarin.PropertyEditing.Tests/BrushPropertyViewModelTests.cs
Xamarin.PropertyEditing/ViewModels/BrushPropertyViewModel.cs

Update the resource selector when editors change

---

Xamarin.PropertyEditing.Tests/PropertiesViewModelTests.cs
Xamarin.PropertyEditing/ViewModels/PropertiesViewModel.cs

[Core] Fix predefined values VM selection

---

Xamarin.PropertyEditing.Tests/MaterialDesignColorViewModelTests.cs
Xamarin.PropertyEditing.Windows/HasItemsToVisibilityConverter.cs
Xamarin.PropertyEditing.Windows/MaterialDesignColorEditorControl.cs
Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
Xamarin.PropertyEditing.Windows/Xamarin.PropertyEditing.Windows.csproj
Xamarin.PropertyEditing/ViewModels/MaterialDesignColorViewModel.cs

Small fixes in visual appearance of the material design color picker, plus a small NRE fix

Bleroy md fit and finish

---

Xamarin.PropertyEditing.Tests/CommonColorTests.cs
Xamarin.PropertyEditing.Windows.Standalone/MainWindow.xaml.cs
Xamarin.PropertyEditing.Windows/BrushChoiceTemplateSelector.cs
Xamarin.PropertyEditing.Windows/BrushEditorControl.cs
Xamarin.PropertyEditing.Windows/BrushTabbedEditorControl.cs
Xamarin.PropertyEditing.Windows/ChoiceControl.cs
Xamarin.PropertyEditing.Windows/EditorPropertySelector.cs
Xamarin.PropertyEditing.Windows/MaterialDesignColorEditorControl.cs
Xamarin.PropertyEditing.Windows/PropertyPresenter.cs
Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
Xamarin.PropertyEditing/Drawing/CommonBrushType.cs
Xamarin.PropertyEditing/Drawing/CommonColor.cs
Xamarin.PropertyEditing/ViewModels/BrushPropertyViewModel.cs
Xamarin.PropertyEditing/ViewModels/MaterialColorScale.cs
Xamarin.PropertyEditing/ViewModels/MaterialDesignColorViewModel.cs
Xamarin.PropertyEditing/Xamarin.PropertyEditing.csproj

This PR:
- Enables the grouped editor for the brush editor
- Fixes related issues with the brush editor
- Cleans up and moves selection logic to VMs

Enable grouped editor for brushes

---

Xamarin.PropertyEditing.Tests/PanelViewModelTests.cs
Xamarin.PropertyEditing.Tests/PropertiesViewModelTests.cs
Xamarin.PropertyEditing/ViewModels/PanelViewModel.cs

[Core] Allow for null grouped types

---

Xamarin.PropertyEditing.Windows/Themes/Resources.xaml

Improve scrollviewer theming

---

Xamarin.PropertyEditing.Windows/EntryPopup.cs
Xamarin.PropertyEditing.Windows/PropertyButton.cs

- Fixes crash on close
- Fixes not closing when clicked off

Fix custom expression popup

---

Xamarin.PropertyEditing.Tests/CombinablePredefinedViewModelTests.cs
Xamarin.PropertyEditing.Tests/PropertyViewModelTests.cs
Xamarin.PropertyEditing/IValidator.cs
Xamarin.PropertyEditing/ViewModels/ConstrainedPropertyViewModel.cs
Xamarin.PropertyEditing/ViewModels/PredefinedValuesViewModel.cs
Xamarin.PropertyEditing/ViewModels/PropertyViewModel.cs
Xamarin.PropertyEditing/Xamarin.PropertyEditing.csproj

To be applied on a IPropertyInfo implementation.

[Core] Add basic value constraint interface

---

Xamarin.PropertyEditing.Windows/PropertyButton.cs
Xamarin.PropertyEditing/Properties/Resources.Designer.cs
Xamarin.PropertyEditing/Properties/Resources.resx
Xamarin.PropertyEditing/ViewModels/ObjectPropertyViewModel.cs
Xamarin.PropertyEditing/ViewModels/PropertyViewModel.cs

[Win] Display resource name in resource pbutton tooltip

---

Xamarin.PropertyEditing.Tests/PropertyViewModelTests.cs
Xamarin.PropertyEditing.Windows/PropertyButton.cs
Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
Xamarin.PropertyEditing/ICanNavigateToSource.cs
Xamarin.PropertyEditing/Properties/Resources.Designer.cs
Xamarin.PropertyEditing/Properties/Resources.resx
Xamarin.PropertyEditing/ViewModels/PropertyViewModel.cs
Xamarin.PropertyEditing/Xamarin.PropertyEditing.csproj

This adds support for the "Convert to Local Value" and "Navigate to [value] source" property button options.

Add convert to local / navigate to source

---

Xamarin.PropertyEditing/Numeric.cs
Xamarin.PropertyEditing/Reflection/ReflectionEnumPropertyInfo.cs

Pre-requisite to moving to .NET standard.

Remove ILGenerator based code

---

Xamarin.PropertyEditing.Windows/BrushEditorControl.cs
Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
Xamarin.PropertyEditing/ViewModels/SolidBrushViewModel.cs

Brush editor bug fixes

---

Xamarin.PropertyEditing.Mac/Controls/BaseEditorControl.cs
Xamarin.PropertyEditing.Mac/Controls/BasePointEditorControl.cs
Xamarin.PropertyEditing.Mac/Controls/Custom/NumericSpinEditor.cs
Xamarin.PropertyEditing.Mac/Controls/Custom/PropertyButton.cs
Xamarin.PropertyEditing.Mac/Controls/Custom/UnfocusableTextField.cs
Xamarin.PropertyEditing.Mac/Resources/LocalizationResources.Designer.cs
Xamarin.PropertyEditing.Mac/Resources/LocalizationResources.resx

Some improvements to the already outstanding accessibility support.

Accessibility fixes

---

Xamarin.PropertyEditing.Mac/Controls/CombinablePropertyEditor.cs
Xamarin.PropertyEditing.Mac/Controls/PointEditorControl.cs
Xamarin.PropertyEditing.Mac/Controls/PropertyEditorControl.cs
Xamarin.PropertyEditing.Mac/Controls/RectangleEditorControl.cs
Xamarin.PropertyEditing.Mac/Controls/SizeEditorControl.cs
Xamarin.PropertyEditing.Mac/PropertyTableDelegate.cs

This is just the first step, but this essentially fixes second-load performance along with some bugs in the combinable property editor regarding reuse.

Improve OSX Performance

---

Xamarin.PropertyEditing.Mac/Controls/BooleanEditorControl.cs

[mac] Fix mixed value booleans

---

Xamarin.PropertyEditing.Tests/MaterialDesignColorViewModelTests.cs
Xamarin.PropertyEditing.Tests/MockObjectEditor.cs
Xamarin.PropertyEditing/ViewModels/BrushPropertyViewModel.cs

Fixes brush type switching on material-matching resource.

Fix material switching on resource

---

Xamarin.PropertyEditing.Tests/Manual/BrushEditor.md
Xamarin.PropertyEditing.Windows/ByteToDoubleConverter.cs
Xamarin.PropertyEditing.Windows/DoubleToAngleConverter.cs
Xamarin.PropertyEditing.Windows/DoubleToPercentageConverter.cs
Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
Xamarin.PropertyEditing.Windows/Xamarin.PropertyEditing.Windows.csproj

Entering an out of range color component coerces the value instead of throwing.

---

Xamarin.PropertyEditing.Tests/CreateResourceViewModelTests.cs
Xamarin.PropertyEditing.Windows/CreateResourceWindow.xaml
Xamarin.PropertyEditing/ViewModels/CreateResourceViewModel.cs

[Core] Remove application resource source requirement

---

Xamarin.PropertyEditing.Tests/MockControls/MockResourceProvider.cs
Xamarin.PropertyEditing.Tests/ResourceSelectorViewModelTests.cs
Xamarin.PropertyEditing/ViewModels/ResourceSelectorViewModel.cs

[Core] Fix shared vs. local resource distinction

---

Xamarin.PropertyEditing.Windows/PropertyButton.cs

[Win] Fix resource tooltips not updating

---

Xamarin.PropertyEditing.Mac/Controls/Custom/ResourceBrushViewController.cs
Xamarin.PropertyEditing.Mac/Controls/Custom/ResourceOutlineView.cs

Closes https://github.com/xamarin/Xamarin.PropertyEditing/issues/373

[Mac] Put the NSOutlineView into a NSScrollView so it scrolls.

---

Xamarin.PropertyEditing.Windows/PropertyEditorPanel.cs
Xamarin.PropertyEditing.Windows/Themes/PropertyEditorPanelStyle.xaml
Xamarin.PropertyEditing/IIconProvider.cs
Xamarin.PropertyEditing/TargetPlatform.cs
Xamarin.PropertyEditing/ViewModels/PanelViewModel.cs
Xamarin.PropertyEditing/Xamarin.PropertyEditing.csproj

[Core/Win] Add type icon support

---

Xamarin.PropertyEditing.Tests/CollectionPropertyViewModelTests.cs
Xamarin.PropertyEditing/ViewModels/CollectionPropertyViewModel.cs

[Core] Handle no-editors in CollectionPropertyViewModel

---

Xamarin.PropertyEditing.Tests/MockEditorProvider.cs
Xamarin.PropertyEditing.Tests/MockObjectEditor.cs
Xamarin.PropertyEditing.Tests/PropertyViewModelTests.cs
Xamarin.PropertyEditing.Windows.Standalone/MainWindow.xaml.cs
Xamarin.PropertyEditing.Windows/EntryPopup.cs
Xamarin.PropertyEditing.Windows/TextBoxEx.cs
Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
Xamarin.PropertyEditing/ICompleteValues.cs
Xamarin.PropertyEditing/ViewModels/PropertyViewModel.cs
Xamarin.PropertyEditing/Xamarin.PropertyEditing.csproj

Completes #375 
Completes #376

Basic autocomplete support

---

Xamarin.PropertyEditing.Mac.Standalone/Main.storyboard
Xamarin.PropertyEditing.Mac.Standalone/ViewController.cs
Xamarin.PropertyEditing.Mac.Standalone/ViewController.designer.cs
Xamarin.PropertyEditing.Mac/PropertyEditorPanel.cs
Xamarin.PropertyEditing.Windows/PropertyEditorPanel.cs

Provides a clear selected items method to use to ensure maximum performance.
Closes #362

Panel.Select()

---

Xamarin.PropertyEditing.Mac/Controls/Custom/UnfocusableButton.cs

[Mac] Up-Down buttons will no longer allow interaction when disabled.

---

Xamarin.PropertyEditing.Tests/MockControls/MockControl.cs
Xamarin.PropertyEditing.Tests/MockControls/MockSampleControl.cs
Xamarin.PropertyEditing.Tests/MockPropertyInfo/MockEnumPropertyInfo.cs
Xamarin.PropertyEditing.Tests/PredefinedValuesViewModelTests.cs
Xamarin.PropertyEditing.Windows/ComboBoxEx.cs
Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
Xamarin.PropertyEditing.Windows/Xamarin.PropertyEditing.Windows.csproj
Xamarin.PropertyEditing/ViewModels/PredefinedValuesViewModel.cs

[Win] Support unconstrained values in editor with predefined values

---

Xamarin.PropertyEditing.Tests/CommonColorTests.cs
Xamarin.PropertyEditing/Drawing/CommonColor.cs

Add `CommonColor.ToArgbHex`

---

Xamarin.PropertyEditing.Tests/MockControls/MockControl.cs
Xamarin.PropertyEditing.Tests/MockControls/MockSampleControl.cs
Xamarin.PropertyEditing.Tests/MockObjectEditor.cs
Xamarin.PropertyEditing.Tests/MockPropertyInfo/MockPropertyInfo.cs
Xamarin.PropertyEditing.Tests/PropertyViewModelTests.cs
Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
Xamarin.PropertyEditing/IHaveInputModes.cs
Xamarin.PropertyEditing/ViewModels/NumericPropertyViewModel.cs
Xamarin.PropertyEditing/ViewModels/PropertyViewModel.cs
Xamarin.PropertyEditing/Xamarin.PropertyEditing.csproj

Input modes

---

Xamarin.PropertyEditing.Mac/Controls/Custom/ChannelEditor.cs
Xamarin.PropertyEditing.Mac/Controls/Custom/ColorComponentEditor.cs
Xamarin.PropertyEditing.Mac/Controls/Custom/ComponentSpinEditor.cs
Xamarin.PropertyEditing.Mac/Controls/Custom/NumericSpinEditor.cs
Xamarin.PropertyEditing.Mac/Controls/Custom/NumericTextField.cs

[Mac] Color picker fixes

---

Xamarin.PropertyEditing.Mac/Controls/Custom/NumericSpinEditor.cs

Avoids premature commits to last color. Fixes #407 and #400.

Don't notify changes for any value change of a spin editor

---

Xamarin.PropertyEditing.Mac/Controls/PanelHeaderEditorControl.cs
Xamarin.PropertyEditing.Mac/PropertyEditorPanel.cs
Xamarin.PropertyEditing.Mac/PropertyTableDataSource.cs
Xamarin.PropertyEditing.Mac/PropertyTableDelegate.cs
Xamarin.PropertyEditing.Mac/Resources/LocalizationResources.Designer.cs
Xamarin.PropertyEditing.Mac/Resources/LocalizationResources.resx
Xamarin.PropertyEditing.Mac/Xamarin.PropertyEditing.Mac.csproj

Closes - https://github.com/xamarin/Xamarin.PropertyEditing/issues/87

[Mac] Initial ObjectName implementation.

---

Xamarin.PropertyEditing.Mac/Controls/PanelHeaderEditorControl.cs
Xamarin.PropertyEditing.Mac/PropertyTableDelegate.cs

[Mac] Icon View implementation

---

Xamarin.PropertyEditing.Mac/Controls/Custom/BrushTabViewController.cs
Xamarin.PropertyEditing.Mac/Controls/Custom/ResourceBrushViewController.cs
Xamarin.PropertyEditing.Mac/Controls/Custom/UnderlinedTabViewController.cs

Video of filtering in action - 
https://www.screencast.com/t/Nc99Xdpfd

[Mac] Add filtering capabilities to brush popUp controller.

---

Xamarin.PropertyEditing.Mac.Standalone/ViewController.cs
Xamarin.PropertyEditing.Mac/PropertyTableDelegate.cs
Xamarin.PropertyEditing.Tests/PanelViewModelTests.cs
Xamarin.PropertyEditing.Windows.Standalone/MainWindow.xaml.cs
Xamarin.PropertyEditing/ViewModels/PanelViewModel.cs

Fix expand

---

Xamarin.PropertyEditing.Mac/Controls/Custom/UnderlinedTextField.cs
Xamarin.PropertyEditing.Mac/Controls/RequestResource/RequestResourceView.cs
Xamarin.PropertyEditing.Mac/Controls/RequestResource/ResourceTableDelegate.cs
Xamarin.PropertyEditing.Mac/Themes/MacThemeManager.cs

As per discussion with @alanmcgovern. Small refactor to handle ~sel inside the Theming call.

[Mac] Refactor GetImageNameForTheme to handle ~sel append internally.

---

Xamarin.PropertyEditing.Mac/Controls/GroupEditorControl.cs

Needs a better fix that uses constraints in the long term.

[Mac] Quick fix for Brush Alignment. 

---

Xamarin.PropertyEditing.Mac/PropertyEditorPanel.cs

Fixes - https://github.com/xamarin/Xamarin.PropertyEditing/issues/487

[Mac] ArrangeByMode should use ViewModel ArrangeModes.

---

Xamarin.PropertyEditing.Windows/CategoryExpander.cs
Xamarin.PropertyEditing.Windows/FilterExpander.cs
Xamarin.PropertyEditing.Windows/Themes/PropertyEditorPanelStyle.xaml
Xamarin.PropertyEditing.Windows/Xamarin.PropertyEditing.Windows.csproj

[Win] Fix uncommon not expanding on search

---

Xamarin.PropertyEditing.Mac/Controls/NumericEditorControl.cs

Fixes https://github.com/xamarin/Xamarin.PropertyEditing/issues/500

Fix Tabbing through all numeric controls.

---

Xamarin.PropertyEditing.Tests/MaterialDesignColorViewModelTests.cs
Xamarin.PropertyEditing/ViewModels/MaterialDesignColorViewModel.cs

[core] Fix no brush -> material

---

Xamarin.PropertyEditing/TargetPlatform.cs
Xamarin.PropertyEditing/ViewModels/PanelViewModel.cs

[core] Add option to autoexpand categories at platform

---

Xamarin.PropertyEditing.Mac.Standalone/Xamarin.PropertyEditing.Mac.Standalone.csproj
Xamarin.PropertyEditing.Mac/Xamarin.PropertyEditing.Mac.csproj

This makes sure they end up in the right directory

[build] Ensure the pngs are copied where we expect

---

Xamarin.PropertyEditing.Windows.Standalone/MainWindow.xaml
Xamarin.PropertyEditing.Windows.Standalone/MainWindow.xaml.cs
Xamarin.PropertyEditing.Windows/Themes/Resources.xaml

This fixes clipping at larger font sizes and fixes alignment in smaller and larger font sizes.

Improve sizing and layout on Windows

---

Xamarin.PropertyEditing.Mac/Controls/BooleanEditorControl.cs
Xamarin.PropertyEditing.Mac/Controls/BrushEditorControl.cs
Xamarin.PropertyEditing.Mac/Controls/CombinablePropertyEditor.cs
Xamarin.PropertyEditing.Mac/Controls/Custom/FocusableBooleanButton.cs
Xamarin.PropertyEditing.Mac/Controls/Custom/FocusableButton.cs
Xamarin.PropertyEditing.Mac/Controls/Custom/FocusableComboBox.cs
Xamarin.PropertyEditing.Mac/Controls/Custom/FocusablePopupButton.cs
Xamarin.PropertyEditing.Mac/Controls/NumericEditorControl.cs
Xamarin.PropertyEditing.Mac/Controls/ObjectEditorControl.cs
Xamarin.PropertyEditing.Mac/Controls/PredefinedValuesEditor.cs
Xamarin.PropertyEditing.Mac/Controls/StringEditorControl.cs
Xamarin.PropertyEditing.Mac/Controls/TypeEditorControl.cs
Xamarin.PropertyEditing.Mac/Xamarin.PropertyEditing.Mac.csproj

Fixes https://github.com/xamarin/Xamarin.PropertyEditing/issues/466

[Mac] When tabbing scroll focused control into view.

---

Xamarin.PropertyEditing.Tests/PanelViewModelTests.cs
Xamarin.PropertyEditing/ViewModels/PanelViewModel.cs

[Core] Fix removing groupable items when not grouped

---

Xamarin.PropertyEditing.Windows/PropertyEditorPanel.cs

This fixes a arrange by name filtering issue on Windows

Fix filtering issues

---

Xamarin.PropertyEditing.Mac/Controls/Custom/SpinnerButton.cs

Fixes regression introduced by #480

[mac] Fix SpinnerButton regression

---

Xamarin.PropertyEditing.Mac/Controls/PropertyContainer.cs
Xamarin.PropertyEditing.Mac/PropertyEditorPanel.cs

Also adds missing `this.` prefix to certain variables.

[Mac] Remove unused variables.

---

Xamarin.PropertyEditing.Mac/PropertyEditorPanel.cs
Xamarin.PropertyEditing.Mac/PropertyList.cs

[mac] Expose header control

---

Xamarin.PropertyEditing.Mac/Controls/CharEditorControl.cs
Xamarin.PropertyEditing.Mac/Controls/EntryPropertyEditor.cs
Xamarin.PropertyEditing.Mac/Controls/StringEditorControl.cs
Xamarin.PropertyEditing.Mac/Controls/TimeSpanEditorControl.cs
Xamarin.PropertyEditing.Mac/PropertyEditorSelector.cs
Xamarin.PropertyEditing.Mac/Resources/LocalizationResources.Designer.cs
Xamarin.PropertyEditing.Mac/Resources/LocalizationResources.resx
Xamarin.PropertyEditing.Mac/Xamarin.PropertyEditing.Mac.csproj
Xamarin.PropertyEditing.Tests/MockControls/MockSampleControl.cs
Xamarin.PropertyEditing/ViewModels/PropertiesViewModel.cs

This PR:
- Refactors common entry elements into a common base class
- Changes string commit behavior to blur/enter like the other editors
- Adds a TimeSpan editor based on new entry base (replacing #477)
- Adds a char editor base on new entry base (replacing #473)

[mac] Refactor & Add TimeSpan / Char editors

---

Xamarin.PropertyEditing.Tests/Xamarin.PropertyEditing.Tests.csproj

Don't ask me how/why this helps :p

[build] Fix test running inside the IDE

---

Xamarin.PropertyEditing.Mac.Standalone/ViewController.cs
Xamarin.PropertyEditing.Mac.Standalone/Xamarin.PropertyEditing.Mac.Standalone.csproj
Xamarin.PropertyEditing.Mac/Controls/Custom/AutoClosePopOver.cs
Xamarin.PropertyEditing.Mac/Controls/Custom/AutocompleteComboBox.cs
Xamarin.PropertyEditing.Mac/Controls/Custom/BasePopOverControl.cs
Xamarin.PropertyEditing.Mac/Controls/Custom/PropertyButton.cs
Xamarin.PropertyEditing.Mac/Controls/CustomExpressionView.cs

Closes - https://github.com/xamarin/Xamarin.PropertyEditing/issues/377

[Mac] Initial implementation of Autocompletion.

---

Xamarin.PropertyEditing.Mac/PropertyList.cs

[Mac] Add Vertical Scroll Bar

---

Xamarin.PropertyEditing.Mac.Standalone/Xamarin.PropertyEditing.Mac.Standalone.csproj
Xamarin.PropertyEditing.Mac/Xamarin.PropertyEditing.Mac.csproj

[Mac] Enable Xamarin.Mac API analysis in the IDE

---

Xamarin.PropertyEditing/Properties/Resources.cs.resx
Xamarin.PropertyEditing/Properties/Resources.de.resx
Xamarin.PropertyEditing/Properties/Resources.es.resx
Xamarin.PropertyEditing/Properties/Resources.fr.resx
Xamarin.PropertyEditing/Properties/Resources.it.resx
Xamarin.PropertyEditing/Properties/Resources.ja.resx
Xamarin.PropertyEditing/Properties/Resources.ko.resx
Xamarin.PropertyEditing/Properties/Resources.pl.resx
Xamarin.PropertyEditing/Properties/Resources.pt-BR.resx
Xamarin.PropertyEditing/Properties/Resources.ru.resx
Xamarin.PropertyEditing/Properties/Resources.tr.resx
Xamarin.PropertyEditing/Properties/Resources.zh-Hans.resx
Xamarin.PropertyEditing/Properties/Resources.zh-Hant.resx

[loc] Updating translations for our strings

---

Xamarin.PropertyEditing.Tests/MockControls/MockControl.cs
Xamarin.PropertyEditing.Tests/MockControls/MockSampleControl.cs
Xamarin.PropertyEditing.Windows/AutoResizingMaskEditorControl.cs
Xamarin.PropertyEditing.Windows/EditorPropertySelector.cs
Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
Xamarin.PropertyEditing.Windows/Themes/VS.Dark.xaml
Xamarin.PropertyEditing.Windows/Xamarin.PropertyEditing.Windows.csproj
Xamarin.PropertyEditing/Common/AutoResizingFlags.cs
Xamarin.PropertyEditing/Properties/Resources.Designer.cs
Xamarin.PropertyEditing/Properties/Resources.resx
Xamarin.PropertyEditing/ViewModels/AutoResizingPropertyViewModel.cs
Xamarin.PropertyEditing/ViewModels/PropertiesViewModel.cs

Windows Autoresizing Editor

---

Xamarin.PropertyEditing.Windows/PropertyButton.cs

.NET Framework 4.8 added the PositionInSet automation property. It also changed the semantics so that if this property is not set it's computed automatically. And it's read by the narrator. The net result is that when proppy is run in a .NET Framework 4.8 app (like Visual Studio), the narrator reads off the position of menu items (e.g. "blah blah menu item 4 of 11"). AND hidden menu items are counted here, which makes those positions wrong, causing this bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1000455.
To work around all of that, we set the PositionInSet property explicitly, when running on .NET Framework 4.8, to be 0. That causes the narrator not to read the position at all, which is how most VS menus behave.

Make narrator not announce menu item posistion

---

Xamarin.PropertyEditing/Properties/Resources.cs.resx
Xamarin.PropertyEditing/Properties/Resources.de.resx
Xamarin.PropertyEditing/Properties/Resources.es.resx
Xamarin.PropertyEditing/Properties/Resources.fr.resx
Xamarin.PropertyEditing/Properties/Resources.it.resx
Xamarin.PropertyEditing/Properties/Resources.ja.resx
Xamarin.PropertyEditing/Properties/Resources.ko.resx
Xamarin.PropertyEditing/Properties/Resources.pl.resx
Xamarin.PropertyEditing/Properties/Resources.pt-BR.resx
Xamarin.PropertyEditing/Properties/Resources.ru.resx
Xamarin.PropertyEditing/Properties/Resources.tr.resx
Xamarin.PropertyEditing/Properties/Resources.zh-Hans.resx
Xamarin.PropertyEditing/Properties/Resources.zh-Hant.resx

Updating translations from 20191210.2 drop.

Translations from 20191210.2

---

bot-provisioning/dependencies.csx

Using:
- Mono 6.8.0.73
- Xamarin.Mac 6.9.0.13
- Xcode 11.3.0

[Mac] Sync with Designer

---

Xamarin.PropertyEditing/Properties/Resources.cs.resx
Xamarin.PropertyEditing/Properties/Resources.de.resx
Xamarin.PropertyEditing/Properties/Resources.es.resx
Xamarin.PropertyEditing/Properties/Resources.fr.resx
Xamarin.PropertyEditing/Properties/Resources.it.resx
Xamarin.PropertyEditing/Properties/Resources.ja.resx
Xamarin.PropertyEditing/Properties/Resources.ko.resx
Xamarin.PropertyEditing/Properties/Resources.pl.resx
Xamarin.PropertyEditing/Properties/Resources.pt-BR.resx
Xamarin.PropertyEditing/Properties/Resources.ru.resx
Xamarin.PropertyEditing/Properties/Resources.tr.resx
Xamarin.PropertyEditing/Properties/Resources.zh-Hans.resx
Xamarin.PropertyEditing/Properties/Resources.zh-Hant.resx

Loc Checkin from Build 20200126.2

---

Xamarin.PropertyEditing.Mac/Controls/Custom/PopoverFocusRestoreDelegate.cs

Might possibly fix one of the traces in [AB#1088162](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1088162)

Remove the KVO observer from the popover window when it closes

---

Xamarin.PropertyEditing.Mac/Controls/PredefinedValuesEditor.cs

Fixes https://github.com/xamarin/Xamarin.PropertyEditing/issues/718

Fix NRE when SelectionChanged is firing on a null object.

---

Xamarin.PropertyEditing.Mac/Controls/CollectionEditorControl.cs

Fix for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1172869

If our control hasn't been created yet, let's skip the check.

---

build/NuGet.Config

[d16-9] Update NuGet.Config

---

loc/cs/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/de/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/es/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/fr/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/it/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/ja/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/ko/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/pl/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/pt-BR/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/ru/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/tr/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/zh-Hans/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/zh-Hant/Xamarin.PropertyEditing/Properties/Resources.resx.lcl

LEGO: Pull request from juno/hb_867398d8-c3a7-4080-9dbc-0b26ebbb32db_20220105210305254 to loc with localized lcls

LEGO: Pull request from juno/hb_867398d8-c3a7-4080-9dbc-0b26ebbb32db_20220105210305254 to loc

---

loc/cs/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/de/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/es/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/fr/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/it/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/ja/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/ko/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/pl/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/pt-BR/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/ru/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/tr/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/zh-Hans/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/zh-Hant/Xamarin.PropertyEditing/Properties/Resources.resx.lcl

LEGO: Pull request from juno/hb_867398d8-c3a7-4080-9dbc-0b26ebbb32db_20220112013440282 to loc with localized lcls

LEGO: Pull request from juno/hb_867398d8-c3a7-4080-9dbc-0b26ebbb32db_20220112013440282 to loc

---

Xamarin.PropertyEditing.Mac/Controls/Custom/DynamicBox.cs

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1455310
Bug 1455310: [Feedback] Editor theme is not correctly updated when the theme changes (VS for Mac 2022 Preview 4)

Fixed NSColor dispose side effect.

---

Xamarin.PropertyEditing.Mac/Controls/Custom/DynamicBox.cs

Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1455310
Bug 1455310: [Feedback] Editor theme is not correctly updated when the theme changes (VS for Mac 2022 Preview 4)
Backport of #787

[d17-0-vsmac] Fixed NSColor dispose side effect.

---

Directory.Build.props
Directory.Build.targets
Xamarin.PropertyEditing/Xamarin.PropertyEditing.csproj

Port MicroBuild Signing Changes to d17-0-vsmac
Including commits:
6359edaa5c81a0d1697a1ad36807b74388f8ebb2 (main change)
626060a19b286ac6d06f63efc31202b9e34b461b (optmization)

Port MicroBuild Signing Changes to d17-0-vsmac

---

loc/cs/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/de/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/it/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/ja/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/ko/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/pt-BR/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/ru/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/zh-Hans/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/zh-Hant/Xamarin.PropertyEditing/Properties/Resources.resx.lcl

LEGO: Pull request from juno/hb_867398d8-c3a7-4080-9dbc-0b26ebbb32db_20220320014841620 to loc with localized lcls

LEGO: Pull request from juno/hb_867398d8-c3a7-4080-9dbc-0b26ebbb32db_20220320014841620 to loc

---

loc/fr/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/pl/Xamarin.PropertyEditing/Properties/Resources.resx.lcl
loc/tr/Xamarin.PropertyEditing/Properties/Resources.resx.lcl

LEGO: Pull request from juno/hb_867398d8-c3a7-4080-9dbc-0b26ebbb32db_20220321014851566 to loc with localized lcls

LEGO: Pull request from juno/hb_867398d8-c3a7-4080-9dbc-0b26ebbb32db_20220321014851566 to loc

---

loc/es/Xamarin.PropertyEditing/Properties/Resources.resx.lcl

LEGO: Pull request from juno/hb_867398d8-c3a7-4080-9dbc-0b26ebbb32db_20220322014803154 to loc with localized lcls

LEGO: Pull request from juno/hb_867398d8-c3a7-4080-9dbc-0b26ebbb32db_20220322014803154 to loc

---

Xamarin.PropertyEditing/Properties/Resources.resx

Fixes [1871578](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1871578/?view=edit)

Update a11y name for "New" button
