xamarin/Xamarin.PropertyEditing

- Xamarin.PropertyEditing.Mac/Controls/BaseNumericEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/ConstraintExtensions.cs
- Xamarin.PropertyEditing.Mac/Controls/EnumEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/StringEditorControl.cs
- Xamarin.PropertyEditing.Mac/Xamarin.PropertyEditing.Mac.csproj
Gives a better UX when resizing the editor column.
Ignore the branch name, I had originally planned to only do the Numeric controls, but it made sense to do all the existing ones under 1 PR.
> Use the Constraint Extensions to give a more unified feel..

- Xamarin.PropertyEditing.Windows/PropertyEditorPanel.cs
The windows PropertyEditorPanel adds static type maps for windows in its ctor, this means that trying to create more than one PropertyEditorPanel in an application will fail.
> Allow more than one PropertyEditorPanel per app

- Xamarin.PropertyEditing.Mac.Standalone/Xamarin.PropertyEditing.Mac.Standalone.csproj
- Xamarin.PropertyEditing.Mac/Controls/PropertyEditorControl.cs
- Xamarin.PropertyEditing.Mac/NSObjectFacade.cs
- Xamarin.PropertyEditing.Mac/PropertyEditorPanel.cs
- Xamarin.PropertyEditing.Mac/PropertyTableDataSource.cs
- Xamarin.PropertyEditing.Mac/PropertyTableDelegate.cs
- Xamarin.PropertyEditing.Mac/ViewModels/MacPanelViewModel.cs
- Xamarin.PropertyEditing.Mac/Xamarin.PropertyEditing.Mac.csproj
- Xamarin.PropertyEditing.Tests/PanelViewModelTests.cs
- Xamarin.PropertyEditing.Windows/PropertyEditorPanel.cs
- Xamarin.PropertyEditing.sln
- Xamarin.PropertyEditing/Extensions.cs
- Xamarin.PropertyEditing/IGroupingList.cs
- Xamarin.PropertyEditing/IMutableLookup.cs
- Xamarin.PropertyEditing/ObservableCollectionEx.cs
- Xamarin.PropertyEditing/ObservableLookup.cs
- Xamarin.PropertyEditing/OrderedDictionary.cs
- Xamarin.PropertyEditing/PropertyArrangeMode.cs
- Xamarin.PropertyEditing/ViewModels/PanelViewModel.cs
- Xamarin.PropertyEditing/ViewModels/PropertiesViewModel.cs
- Xamarin.PropertyEditing/Xamarin.PropertyEditing.csproj
This implements filter searching and arranging on Mac. It does temporarily break the tabbing fix introduced just before as that was based on a regular `NSTableView` and not an `NSOutlineView`. We'll fix that separately in the interest of getting this in.
> Mac search and arrange

- Xamarin.PropertyEditing.Mac/Controls/BaseRectangleEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/BooleanEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/CGRectEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/PointEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/PredefinedValuesEditor.cs
- Xamarin.PropertyEditing.Mac/Controls/StringEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/UnfocusableTextField.cs
- Xamarin.PropertyEditing.Mac/PropertyEditorPanel.cs
- Xamarin.PropertyEditing.Mac/PropertyTableDelegate.cs
- Xamarin.PropertyEditing.Mac/Xamarin.PropertyEditing.Mac.csproj
Larry and Sandy pointed out that when CALayer backing is turned on the Property Label stop rendering, until a column resize occurs. My switching to using a NSTextField, instead of NSTextView, under the hood, we have  solution that works when CALayer is on, without requiring a column resize to see things properly.
> Fixes to ensure Unfocusable Labels display correctly when Layering is turned on. 

- Xamarin.PropertyEditing.Mac/Controls/BaseNumericEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/BaseRectangleEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/BooleanEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/CGPointEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/CGSizeEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/IntegerNumericEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/PointEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/PredefinedValuesEditor.cs
- Xamarin.PropertyEditing.Mac/Controls/PropertyEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/SizeEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/StringEditorControl.cs
Only setting the Accessibility.Title seems to be enough to give users enough information for each Property.
> Initial Accessibility support for our editors.

- Xamarin.PropertyEditing.Mac/PropertyTableDelegate.cs
Need to return a row height especially for group headers as they don't have
an editor associated. Also, identifiers are not unique to properties, but
to property types, so fixing the discrepancy.
Fixes #49
> [mac] Fix row height and identifiers

- Xamarin.PropertyEditing.Tests/PropertyViewModelTests.cs
- Xamarin.PropertyEditing/IAvailabilityConstraint.cs
- Xamarin.PropertyEditing/ViewModels/PropertyViewModel.cs
This expands `IAvailabilityConstraint` to indicate `IPropertyInfo`s that would trigger a change and implements the logic for querying it into the VM.
> [Core] Availability constraints

- Xamarin.PropertyEditing.Tests/AsyncWorkQueueTests.cs
- Xamarin.PropertyEditing/AsyncWorkQueue.cs
This fixes an issue (demonstrated in included test) where a
child/sibling to another requester is added when that requester is not
the active. The logic that was present in the reqest to set related
requester workers to active was not present when the queue was advanced.
This also significantly reduces the work the request work method does by
simply tracking the active requester. The original comment about small
queues turned out to be false and it is likely to see queues as long as
2x the number of properties.
> [Core] Fix AsyncWorkQueue

- Xamarin.PropertyEditing.Tests/MultiAvailabilityConstraintTests.cs
- Xamarin.PropertyEditing.Tests/Xamarin.PropertyEditing.Tests.csproj
- Xamarin.PropertyEditing/MultiAvailabilityConstraint.cs
- Xamarin.PropertyEditing/Xamarin.PropertyEditing.csproj
Implementation of IAvailabilityConstraint that ors together groups of
anded availability constraints. Written for a target platform, but
generic enough to be included here with tests.
> [Core] Add MultiAvailabilityConstraint

- Xamarin.PropertyEditing.Mac.Standalone/Xamarin.PropertyEditing.Mac.Standalone.csproj
Mono has broken API with Xamarin.Mac again:
Undefined symbols for architecture x86_64:
"_mono_profiler_startup_log", referenced from:
Disabling this as we don't use it anyway. Now we can
compile with newer deps.
> [build] Disable profiling

- Xamarin.PropertyEditing.Tests/PropertyViewModelTests.cs
- Xamarin.PropertyEditing/ViewModels/PropertyViewModel.cs
This was happening specifically when switching fast enough from one inspected mock editable object to another in the Windows standalone app.
> Fix null ref when getting ValueSource if value is null

- Xamarin.PropertyEditing.Mac/Controls/BaseNumericEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/BaseRectangleEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/BooleanEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/CGPointEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/CGSizeEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/PointEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/PredefinedValuesEditor.cs
- Xamarin.PropertyEditing.Mac/Controls/SizeEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/StringEditorControl.cs
- Xamarin.PropertyEditing.Mac/PropertyEditorPanel.cs
- Xamarin.PropertyEditing.Mac/Xamarin.PropertyEditing.Mac.csproj
- Xamarin.PropertyEditing/ViewModels/EnumPropertyViewModel.cs
- Xamarin.PropertyEditing/ViewModels/PredefinedValuesViewModel.cs
- Xamarin.PropertyEditing/Xamarin.PropertyEditing.csproj
This removes the requirement to use the netfx-System.StringResources package to codegen strongly-typed helpers, and fixes a build problem when the projects are included in other solutions. It is a workaround.
> Replace strongly-typed resource usage with string.Format calls

- Xamarin.PropertyEditing.Tests/ObservableLookupTests.cs
- Xamarin.PropertyEditing.Tests/PanelViewModelTests.cs
- Xamarin.PropertyEditing.Windows/CategoryExpander.cs
- Xamarin.PropertyEditing.Windows/GroupEditorControl.cs
- Xamarin.PropertyEditing.Windows/Themes/PropertyEditorPanelStyle.xaml
- Xamarin.PropertyEditing.Windows/Xamarin.PropertyEditing.Windows.csproj
- Xamarin.PropertyEditing/CategoryComparer.cs
- Xamarin.PropertyEditing/ObservableLookup.cs
- Xamarin.PropertyEditing/ViewModels/PanelViewModel.cs
- Xamarin.PropertyEditing/Xamarin.PropertyEditing.csproj
This PR:
- Closed #93, making the category expansion/closure remember and filtering auto-expand categories
- Fixes a bug leaving empty categories in place when cleared from grouped properties
- Fixes a crash from the group editor control metadata override.
> Windows category memory

- Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
The property popup menu does not apply when the the property
is readonly so don't show it.  Fixes #123
> Only enable the property menu when CanWrite is true

- Xamarin.PropertyEditing.Tests/MockControls/MockResourceProvider.cs
- Xamarin.PropertyEditing.Tests/MockObjectEditor.cs
- Xamarin.PropertyEditing.Tests/PropertyViewModelTests.cs
- Xamarin.PropertyEditing.Tests/ResourceSelectorViewModelTests.cs
- Xamarin.PropertyEditing.Tests/Xamarin.PropertyEditing.Tests.csproj
- Xamarin.PropertyEditing.Windows.Standalone/MainWindow.xaml.cs
- Xamarin.PropertyEditing.Windows/PropertyButton.cs
- Xamarin.PropertyEditing.Windows/PropertyEditorPanel.cs
- Xamarin.PropertyEditing.Windows/ResourceSelectorWindow.xaml
- Xamarin.PropertyEditing.Windows/ResourceSelectorWindow.xaml.cs
- Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
- Xamarin.PropertyEditing.Windows/Themes/VS.Dark.xaml
- Xamarin.PropertyEditing.Windows/Themes/VS.Light.xaml
- Xamarin.PropertyEditing.Windows/Xamarin.PropertyEditing.Windows.csproj
- Xamarin.PropertyEditing/IObjectEditor.cs
- Xamarin.PropertyEditing/IResourceProvider.cs
- Xamarin.PropertyEditing/Properties/Resources.Designer.cs
- Xamarin.PropertyEditing/Properties/Resources.resx
- Xamarin.PropertyEditing/Resource.cs
- Xamarin.PropertyEditing/ResourceSource.cs
- Xamarin.PropertyEditing/ValueSource.cs
- Xamarin.PropertyEditing/ViewModels/PropertiesViewModel.cs
- Xamarin.PropertyEditing/ViewModels/PropertyViewModel.cs
- Xamarin.PropertyEditing/ViewModels/ResourceRequestedEventArgs.cs
- Xamarin.PropertyEditing/ViewModels/ResourceSelectorViewModel.cs
- Xamarin.PropertyEditing/Xamarin.PropertyEditing.csproj
This PR:
- Flushes out the resources API
- Adds basic brush preview templates (useful for the brush editor)
- Adds documentation and clarifies some SetValue behavior
- Adds the basis for a resource selector window
While we don't yet have a design for a resource selector window, the basics of one largely won't change from the internals perspective. As such this adds a basic one based on the type selector window that we can adjust once we have designs. The complete experience of the standin helps to test and make sure the rest of the internals are working as expected.
> Basic Windows Resources

- Xamarin.PropertyEditing.Windows/Xamarin.PropertyEditing.Windows.csproj
- Xamarin.PropertyEditing/Properties/AssemblyInfo.cs
- Xamarin.PropertyEditing/Xamarin.PropertyEditing.csproj
Updated so if a ..\..\..\xamarin.snk file exists (which it will when we build proppy as git submodule under external/Xamarin.PropertyEditing), then we strong name the assemblies. Also updated InternalsVisibleTo to include public key when we build strong named, via ifdef.
Note that there's still one outstanding issue here, with this build error:
```Xamarin.PropertyEditing\Xamarin.PropertyEditing.Windows\Themes\PropertyEditorPanelStyle.xaml(147,25): error MC3064: Only public or internal classes can be used within markup. 'EventViewModel' type is not public or internal.```
It seems like there's some bug with InternalsVisibleTo that includes a public key not working properly from XAML files. But we can fix that (somehow) separately.
> Added (conditional) strong naming to builds

- Xamarin.PropertyEditing.Windows/Themes/PropertyEditorPanelStyle.xaml
This effectively removes the reference to a type from a different and potentially signed assembly from XAML, and makes the build pass when the assemblies are signed. It doesn't change behavior.
> Remove DataType qualifier on eventsPane DataTemplate

- Xamarin.PropertyEditing.Tests/Manual/BrushEditor.md
- Xamarin.PropertyEditing.Tests/SolidBrushPropertyViewModelTests.cs
- Xamarin.PropertyEditing.Tests/Xamarin.PropertyEditing.Tests.csproj
- Xamarin.PropertyEditing.Windows.Standalone/MainWindow.xaml.cs
- Xamarin.PropertyEditing.Windows.Standalone/MockedSampleControlButton.cs
- Xamarin.PropertyEditing.Windows/BrushEditorControl.cs
- Xamarin.PropertyEditing.Windows/BrushTabbedEditorControl.cs
- Xamarin.PropertyEditing.Windows/ColorComponentBox.cs
- Xamarin.PropertyEditing.Windows/ColorComponentsEditorControl.cs
- Xamarin.PropertyEditing.Windows/ColorEditorControlBase.cs
- Xamarin.PropertyEditing.Windows/CurrentColorEditorControl.cs
- Xamarin.PropertyEditing.Windows/HueEditorControl.cs
- Xamarin.PropertyEditing.Windows/PropertyPresenter.cs
- Xamarin.PropertyEditing.Windows/ShadeEditorControl.cs
- Xamarin.PropertyEditing.Windows/SolidBrushEditorControl.cs
- Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
- Xamarin.PropertyEditing.Windows/Themes/VS.Dark.xaml
- Xamarin.PropertyEditing.Windows/Themes/VS.Light.xaml
- Xamarin.PropertyEditing/BrushPropertyInfo.cs
- Xamarin.PropertyEditing/Drawing/CommonColor.cs
- Xamarin.PropertyEditing/Properties/Resources.Designer.cs
- Xamarin.PropertyEditing/Properties/Resources.resx
- Xamarin.PropertyEditing/ViewModels/BrushPropertyViewModel.cs
- Xamarin.PropertyEditing/ViewModels/SolidBrushViewModel.cs
Solid brush editor moved to a tab in preparation for future color resource tab. Also put a property presenter around, and did the same to the color space drop-down.
Note: the view model is not 100% ready for bindings and resources on deep properties such as the opacity, color space, and solid brush color. This is known, so I added TODOs in there to that effect.
> Bleroy brush editor 2

- Xamarin.PropertyEditing.Windows/Themes/PropertyEditorPanelStyle.xaml
This is just step 1, things don't seem to be recycled at the level we need for maximum performance, but this helps. Before:
After:
> [Win] Fix editor virtualization

- Xamarin.PropertyEditing.Tests/BoolViewModelTests.cs
- Xamarin.PropertyEditing.Tests/BytePropertyViewModelTests.cs
- Xamarin.PropertyEditing.Tests/ConstrainedPropertyViewModelTests.cs
- Xamarin.PropertyEditing.Tests/FloatingPropertyViewModelTests.cs
- Xamarin.PropertyEditing.Tests/IntegerPropertyViewModelTests.cs
- Xamarin.PropertyEditing.Tests/MockPropertyInfo/MockPropertyInfo.cs
- Xamarin.PropertyEditing.Tests/NumericTests.cs
- Xamarin.PropertyEditing.Tests/NumericViewModelTests.cs
- Xamarin.PropertyEditing.Tests/PropertyViewModelTests.cs
- Xamarin.PropertyEditing.Windows/EditorPropertySelector.cs
- Xamarin.PropertyEditing/ISelfConstrainedPropertyInfo.cs
- Xamarin.PropertyEditing/Numeric.cs
- Xamarin.PropertyEditing/ViewModels/ConstrainedPropertyViewModel.cs
- Xamarin.PropertyEditing/ViewModels/NumericPropertyViewModel.cs
- Xamarin.PropertyEditing/ViewModels/PropertiesViewModel.cs
- Xamarin.PropertyEditing/ViewModels/PropertyViewModel.cs
This adds support for nullable and unset for numeric and bools. It is likely to break Mac, but we're going to ignore that for the moment given the time constraints. It also contains a rather large breaking change in that get/set now use `Nullable<T>` instead of `T`, regardless of what the `IPropertyInfo.Type` reports.
It's possible we may be able to address this by calling with the right generic, so for the moment implementers should support both scenarios to avoid future breakage.
> [Core] Support nullable and unset primitives

- Xamarin.PropertyEditing.Windows/BrushChoiceTemplateSelector.cs
- Xamarin.PropertyEditing.Windows/BrushTabbedEditorControl.cs
- Xamarin.PropertyEditing.Windows/PropertyButton.cs
- Xamarin.PropertyEditing.Windows/ResourceBrushEditorControl.cs
- Xamarin.PropertyEditing.Windows/ResourceSelectorWindow.xaml.cs
- Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
- Xamarin.PropertyEditing.Windows/Xamarin.PropertyEditing.Windows.csproj
- Xamarin.PropertyEditing/Properties/Resources.Designer.cs
- Xamarin.PropertyEditing/Properties/Resources.resx
- Xamarin.PropertyEditing/ViewModels/BrushPropertyViewModel.cs
- Xamarin.PropertyEditing/ViewModels/PropertyViewModel.cs
This is a PR to fix #173
It add a resource selector tab for the brush editor and a few model related changes to allow binding the selected resource.  It's currently based off the material design branch to make tracking that simpler.
> Implement resource brush selection

- Xamarin.PropertyEditing.Mac/Xamarin.PropertyEditing.Mac.csproj
If a xamarin.snk key file is found, sign the mac assembly the same
as we do on Windows.
> Added strong naming of mac assembly

- Xamarin.PropertyEditing.Windows/NumericUpDownControl.cs
- Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
We already constrain numeric editors in the VM, no other use cases of
the control itself use min/max and if they did it should probably move
to a VM anyway.
> [Win] Remove up/down minmax

- Xamarin.PropertyEditing.Tests/MockEditorProvider.cs
- Xamarin.PropertyEditing.Tests/MockObjectEditor.cs
- Xamarin.PropertyEditing.Windows.Standalone/MainWindow.xaml.cs
- Xamarin.PropertyEditing.Windows/Themes/PropertyEditorPanelStyle.xaml
This hides the name entry and label when the object is not nameable.
> Hide the name editor when the object is not nameable

- Xamarin.PropertyEditing.Windows.Standalone/MainWindow.xaml.cs
- Xamarin.PropertyEditing.Windows.Standalone/Xamarin.PropertyEditing.Windows.Standalone.csproj
- Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
If the icons exist in the expected `..\..\..\Xamarin.Designer.VisualStudio\src\VisualStudio.Designer\ProppyIcons.xaml` path relative to the project, the resource is included and merged at runtime. This enables us to verify that the icons display in this context, which should make sure they also do so in VS. Later, we should have a proper fallback to a default set of icons.
> Enable the Windows standalone app to use VS icons

- Xamarin.PropertyEditing.Windows.Standalone/App.xaml
- Xamarin.PropertyEditing.Windows/ObjectEditorControl.cs
- Xamarin.PropertyEditing.Windows/PropertyButton.cs
- Xamarin.PropertyEditing.Windows/PropertyEditorPanel.cs
- Xamarin.PropertyEditing.Windows/ResourceSelectorWindow.xaml.cs
- Xamarin.PropertyEditing.Windows/TypeSelectorWindow.xaml.cs
Fixes #183 
Consumers should remove the manual `Resources.xaml` add they've included.
> [Win] Auto-include resources and pass merges to subwindows

- Xamarin.PropertyEditing/ViewModels/PropertyViewModel.cs
This avoids a crash with multiple selected non nullable properties.  I'm not certain this is the correct way to handle that case.
> Handle multiselection without crashing

- Xamarin.PropertyEditing.Windows/BrushBoxControl.cs
- Xamarin.PropertyEditing.Windows/BrushToDarknessConverter.cs
- Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
- Xamarin.PropertyEditing/ViewModels/MaterialColorScale.cs
- Xamarin.PropertyEditing/ViewModels/MaterialDesignColorViewModel.cs
The threshold for switching from white to black text over a Material Design color used to be based on a brightness threshold. With this change, the switch is based on manual metadata for each palette, which ensures that the text is always readable, even on colors that give bad contrast with white text even for low brightness, such as yellow.
> Handle manual setting of the material color foreground color

- Xamarin.PropertyEditing.Windows/ChoiceControl.cs
In VS, unloading controls seems to want to unset their styles and
therefore their templates which triggers updates not seen in the
standalone app.
This fixes the container generator status change when the template is
changed to null. When it's null we don't care about the contents so
we'll just return.
> [Win] Fix NRE in ChoiceControl on unload

- Xamarin.PropertyEditing.Windows/BrushTabbedEditorControl.cs
When Material Design is not supported by the host platform, the filtering logic uses a cast that is no longer valid. This fixes it.
> Fix bad casting in brush tabs

- Xamarin.PropertyEditing.Tests/CombinablePredefinedViewModelTests.cs
- Xamarin.PropertyEditing/ViewModels/CombinablePropertyViewModel.cs
This PR:
- Fixes constraints to work on combinable values
- Fixes a broken test to not NRE. That test fails and it's my intention to leave it failing until I can fix it. It is specifically related to multi-selection which is currently disabled in our consumers.
> Fix constraints for combinable

- Xamarin.PropertyEditing.Tests/MockControls/MockControl.cs
Missing description parameter.
Without this fix StandAlone on Mac crashes, before the nullable crash :)
I need this fix before I can rebase the Nullable changes for Mac.
> Fix to stop crash when Enumeration type is created. 

- Xamarin.PropertyEditing.Tests/PropertyViewModelTests.cs
- Xamarin.PropertyEditing/ViewModels/PropertyViewModel.cs
And mark .Value as for direct input only. Any other method of changing
the value needs its own path. Fixes #255
> [Core] Ignore raw value changes from direct input

- Xamarin.PropertyEditing.Tests/BytePropertyViewModelTests.cs
- Xamarin.PropertyEditing.Tests/PropertyViewModelTests.cs
- Xamarin.PropertyEditing/ViewModels/CombinablePropertyViewModel.cs
- Xamarin.PropertyEditing/ViewModels/PropertyViewModel.cs
the ValueSources change is causing test failures in:
* NullableBoolViewModelTests
* NullableIntegerPropertyViewModelTests
I haven't had a chance to look into it yet beyond seeing that the model is no longer considered nullable.
> Add test cases for empty editor lists and null ValueInfo<T> values

- Xamarin.PropertyEditing.Tests/MockPropertyInfo/MockBrushPropertyInfo.cs
This is so the standalone apps can properly see brush properties when multiple objects are selected. Fixes #277
> Make MockBrushPropertyInfo IEquatable

- Xamarin.PropertyEditing.Tests/Xamarin.PropertyEditing.Tests.csproj
- Xamarin.PropertyEditing.Windows.Standalone/Xamarin.PropertyEditing.Windows.Standalone.csproj
This fixes the inclusion of the Nunit prop file and of the icons file in the case where PropertyEditing is a submodule of the designer repo, and keeping the side-by-side configuration working.
> Improve designer integrated build

- Xamarin.PropertyEditing.Windows/Themes/PropertyEditorPanelStyle.xaml
Removes the scrollviewer from group child lists.
Fixes #293
> [Win] Fix scrolling in grouped mode

- .gitignore
This is helpful in particular on the mac when not building side-by-side with the designer repo.
> Ignore packages dir

- Xamarin.PropertyEditing.Tests/MockObjectEditor.cs
- Xamarin.PropertyEditing.Windows.Standalone/MockedSampleControlButton.cs
- Xamarin.PropertyEditing/Drawing/CommonBrushType.cs
- Xamarin.PropertyEditing/Drawing/CommonColor.cs
- Xamarin.PropertyEditing/Drawing/CommonColorToCommonBrushConverter.cs
- Xamarin.PropertyEditing/ViewModels/BrushPropertyViewModel.cs
- Xamarin.PropertyEditing/ViewModels/PropertiesViewModel.cs
- Xamarin.PropertyEditing/Xamarin.PropertyEditing.csproj
It also introduces the ability to filter what brush types can be used, property by property.
I had to introduce some type converter extensibility when resolving resource values that didn't feel 100% right when I wrote it: I wish we could do that without adding a burden to the editor author, but couldn't find a better way. If I missed one, please do tell, and I'll happily change that part.
> Allow for properties of type CommonColor.

- NuGet.Config
- build/NuGet.Config
Touchdown is only needed for localization and we only run that rarely,
so remove that source from the standard NuGet.Config so we don't have
to query it as part of our normal build/restore process.
> [build] Remove touchdown from the normal restore path

- Xamarin.PropertyEditing.Tests/SimpleCollectionViewTests.cs
- Xamarin.PropertyEditing/ViewModels/SimpleCollectionView.cs
This is to enable macOS to skip enumerating when they need to hit specific rows.
> [Core] Add IList to SimpleCollectionView

- Xamarin.PropertyEditing.Mac/Controls/Custom/MaterialBrushEditorViewController.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/MaterialView.cs
This cleans up the ViewModel used in MaterialView and fixes a performance regression that was introduced  when MaterialView was turned into a NotifyingView.
> [mac] switch MaterialView to using MaterialDesignViewModel

- Xamarin.PropertyEditing.Mac/Controls/BrushEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/UnderlinedTextField.cs
@vancura asked for two small updates to the latest version.  Centering the popup over the color swatch and reducing the Tab icon padding.  These are those changes
> Mac color editor design review

- Xamarin.PropertyEditing.Mac/PropertyEditorPanel.cs
- Xamarin.PropertyEditing.Tests/BrushPropertyViewModelTests.cs
- Xamarin.PropertyEditing.Tests/PropertyViewModelTests.cs
- Xamarin.PropertyEditing.Windows/PropertyButton.cs
- Xamarin.PropertyEditing/ViewModels/BrushPropertyViewModel.cs
- Xamarin.PropertyEditing/ViewModels/PropertyViewModel.cs
Now that ResourceProvider is in the platform remove it from PropertyViewModel and fix up the references. This fixes the runtime problems that slipped in with the bindings related changes.
> Move resource provider

- Xamarin.PropertyEditing.Tests/MockObjectEditor.cs
- Xamarin.PropertyEditing.Tests/PropertyViewModelTests.cs
- Xamarin.PropertyEditing/ViewModels/PropertyViewModel.cs
This reverts an invalid change with setting resources and fixes an issue from the source/value descriptor break out when setting resource values.
> Fix resource issues

- Xamarin.PropertyEditing.Mac/Controls/Custom/UnfocusableButton.cs
Previous code was removing the existing tracking area, which was wrong. We want to add the new tracking area for MouseEntered/Exited.
> [Mac] Fix PropertyButton Tooltips.

- Xamarin.PropertyEditing.Windows/ObjectEditorControl.cs
- Xamarin.PropertyEditing.Windows/PropertyButton.cs
Fixes #378 
What's really happening is the control is loaded and then unloaded on the switch to grouped, but the VM still lives. Since `e.OldValue` turns out to be unreliable in `DataContextChanged`, we're actually keeping the control alive and attached via the VM resulting in a dead editor receiving the event to open the object editor.
> Fix new object crash after reloading

- Xamarin.PropertyEditing.Mac/PropertyEditorPanel.cs
This was a design requirement, that I'd totally missed.
The real change in this PR is within the Constraints in lines - https://github.com/xamarin/Xamarin.PropertyEditing/blob/2e2020db56f2fbcc76c8fbb50a7abd05d6fcf7c6/Xamarin.PropertyEditing.Mac/PropertyEditorPanel.cs#L180-L189
The other changes are purely adhering to coding standards and removing CGRect calls that are useless when setting `TranslatesAutoresizingMaskIntoConstraints = false`.
> [Mac] Swap property search filter & arrange mode positions. Better UX.

- Xamarin.PropertyEditing.Mac/Controls/Custom/BrushTabViewController.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/UnderlinedTabViewController.cs
- Xamarin.PropertyEditing/IReadOnlyOrderedDictionary.cs
- Xamarin.PropertyEditing/OrderedDictionary.cs
- Xamarin.PropertyEditing/ViewModels/BrushPropertyViewModel.cs
- Xamarin.PropertyEditing/Xamarin.PropertyEditing.csproj
This fixes visual and performance issues when the brush editor is used/reused inline:
- Tabs are no longer destroyed and rebuilt every time a tab is removed
- Tabs are no longer destroyed and rebuilt every time a tab is added
This has the side-effect of no longer destroying the actual active brush type editor itself.
> Fix brush editor reuse

- Xamarin.PropertyEditing.Mac/Controls/Custom/UnderlinedTabViewController.cs
AddTabViewItem just proxies to Insert, we don't need both or we duplicate.
> [mac] Fix duplicate tabs

- Xamarin.PropertyEditing.Mac/Controls/Custom/ColorComponentEditor.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/SolidColorBrushEditor.cs
Putting more safeguards in-place against failing frame dimension assumptions, thus averting crashes.
> Fix color picker layout issues with unexpected popup dimensions

- Xamarin.PropertyEditing.Mac/Controls/PanelHeaderEditorControl.cs
Closes - https://github.com/xamarin/Xamarin.PropertyEditing/issues/370
> [Mac] Initial TypeName implementation.

- Xamarin.PropertyEditing.Mac/Controls/ThicknessEditorControl.cs
- Xamarin.PropertyEditing.Mac/PropertyTableDelegate.cs
- Xamarin.PropertyEditing.Mac/Resources/LocalizationResources.Designer.cs
- Xamarin.PropertyEditing.Mac/Resources/LocalizationResources.resx
- Xamarin.PropertyEditing.Mac/Xamarin.PropertyEditing.Mac.csproj
- Xamarin.PropertyEditing.Tests/MockControls/MockSampleControl.cs
I've made this behave similar to how the Rectangle Editor works, so as such it does not support any images in this version to replace the  label text, just as the Point Editor doesn't support images right now. So it is consistent with what we currently have. The idea being that adding images would require asking Vaclav for extra art. Hope to come back to this closer to release to add the images into this and the Point editor.
> [Mac] Initial implemention of Thickness Editor.

- Xamarin.PropertyEditing.Mac/Controls/Custom/BrushTabViewController.cs
The controller goes through the theme manager, and gracefully skips the icons if they're not found, instead of throwing from the depths of AppKit.
> Improve icon retrieval from brush tab view controller

- Xamarin.PropertyEditing.Mac/Controls/PredefinedValuesEditor.cs
The struct constraint is breaking enumerations described with strings.
> Remove struct constraint on mac predefined values editor

- Xamarin.PropertyEditing.Mac/PropertyEditorPanel.cs
This is what was throwing me when theme changing. So Themes ARE changing correctly, but this hardcoded colour made it appear that it wasn't
Some slight accessor changes to make the code more to standard, while I was there.
> [Mac] Remove hard coded colour on Arrange By label.

- Xamarin.PropertyEditing.Mac/Controls/BrushEditorControl.cs
Fixes https://github.com/xamarin/Xamarin.PropertyEditing/issues/359
> [Mac] Centre Preview inside brush popup control.

- Xamarin.PropertyEditing.Mac/Controls/BaseEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/BasePointEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/BaseRectangleEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/BooleanEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/BrushEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/ConstraintExtensions.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/BasePopOverControl.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/ColorComponentEditor.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/MaterialBrushEditorViewController.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/NumericSpinEditor.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/ResourceOutlineViewDelegate.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/UnfocusableTextField.cs
- Xamarin.PropertyEditing.Mac/Controls/CustomExpressionView.cs
- Xamarin.PropertyEditing.Mac/Controls/EditorContainer.cs
- Xamarin.PropertyEditing.Mac/Controls/ErrorMessageView.cs
- Xamarin.PropertyEditing.Mac/Controls/NumericEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/PanelHeaderEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/PointEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/PredefinedValuesEditor.cs
- Xamarin.PropertyEditing.Mac/Controls/RatioEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/RectangleEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/RequestResource/RequestResourcePanel.cs
- Xamarin.PropertyEditing.Mac/Controls/RequestResource/RequestResourcePreviewPanel.cs
- Xamarin.PropertyEditing.Mac/Controls/RequestResource/ResourceTableDelegate.cs
- Xamarin.PropertyEditing.Mac/Controls/SizeEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/StringEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/ThicknessEditorControl.cs
- Xamarin.PropertyEditing.Mac/PropertyEditorPanel.cs
- Xamarin.PropertyEditing.Mac/PropertyTableDelegate.cs
Fixes #463 
Brushes:
Resources:
> [Mac]Fix vertical alignment of labels in resource lists.

- Xamarin.PropertyEditing.Mac/PropertyTableDelegate.cs
- Xamarin.PropertyEditing/ViewModels/PropertiesViewModel.cs
It seems that in this branch, using `EnumPropertyViewModel` causes no
editor to be created. `PropertyTableDelegate` does not check for null
editors, resulting in NREs. Add checks, just in case.
In my testing, only `CALayer.ContentsFormat` ends up using
`EnumPropertyViewModel`. For now, comment-out the section in
`PropertiesViewModel.GetViewModel` that creates `EnumPropertyViewModel`,
so that at least a `StringPropertyViewModel` is created.
> Workbooks: Prevent NRE on CALayer.ContentsFormat

- Xamarin.PropertyEditing.Tests/CollectionPropertyViewModelTests.cs
- Xamarin.PropertyEditing.Windows/CollectionEditorWindow.xaml.cs
- Xamarin.PropertyEditing.Windows/ObjectEditorControl.cs
- Xamarin.PropertyEditing/ViewModels/CollectionPropertyViewModel.cs
- Xamarin.PropertyEditing/ViewModels/ObjectPropertyViewModel.cs
This allows for a request to be answered in the future, preventing the
implementing UI to have to block for a response during the event
request. Primarily used to support Mac as it uses popovers rather than
whole windows.
> [Core] Use a Task result for type request

- Xamarin.PropertyEditing.Mac/Controls/BrushEditorControl.cs
This does not fix keyboard navigation inside the popup, but makes it possible to open the popup using the keyboard once the brush property is focused.
> Improve keyboard navigation for brush editors

- Xamarin.PropertyEditing.Mac/PropertyTableDataSource.cs
- Xamarin.PropertyEditing.Mac/PropertyTableDelegate.cs
- Xamarin.PropertyEditing.Tests/MockControls/MockControl.cs
- Xamarin.PropertyEditing.Tests/MockControls/MockSampleControl.cs
- Xamarin.PropertyEditing.Tests/MockPropertyInfo/MockBrushPropertyInfo.cs
- Xamarin.PropertyEditing.Tests/MockPropertyInfo/MockPropertyInfo.cs
- Xamarin.PropertyEditing.Tests/OrderedDictionaryTests.cs
- Xamarin.PropertyEditing.Tests/PanelViewModelTests.cs
- Xamarin.PropertyEditing.Tests/Xamarin.PropertyEditing.Tests.csproj
- Xamarin.PropertyEditing.Windows/PropertyEditorPanel.cs
- Xamarin.PropertyEditing.Windows/Themes/PropertyEditorPanelStyle.xaml
- Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
- Xamarin.PropertyEditing/IPropertyInfo.cs
- Xamarin.PropertyEditing/OrderedDictionary.cs
- Xamarin.PropertyEditing/Reflection/ReflectionPropertyInfo.cs
- Xamarin.PropertyEditing/ViewModels/PanelViewModel.cs
This adds support for low-frequency properties in the core and Windows. Mac will arrange the properties to the bottom of a section but doesn't currently hide them.
Completes #433 
Completes #435
> Support low-frequency properties

- Xamarin.PropertyEditing.Windows.Standalone/MainWindow.xaml
- Xamarin.PropertyEditing.Windows/PropertyEditorPanel.cs
Allows a host to set `PropertyEditorPanel.ArrangeMode` directly to define the default arrange (#475) mode.
> [Win] Respect host-set arrange mode

- Xamarin.PropertyEditing.Mac/Controls/Custom/DynamicFillBox.cs
- Xamarin.PropertyEditing.Mac/PropertyEditorPanel.cs
DynamicFillBox now allows for colors to be not found, sort of a hack fix
to deal with the fact that we allow PropertyEditorPanel to be used in
xibs, so we can't demand a IHostResourceProvider in the ctor, we have to
accept it later.
This also fixes the fact that the header theming wouldn't update when
the resource provider changes.
> [mac] Fix editor panel theme handling

- Xamarin.PropertyEditing.Mac.Standalone/Main.storyboard
...editor dimensions.
Allows us to see more closely what it would look like inside an IDE/App.
> Resize storyboard so on startup stand-alone is closer to property... 

- Xamarin.PropertyEditing.Tests/PanelViewModelTests.cs
- Xamarin.PropertyEditing/ViewModels/PanelViewModel.cs
- Xamarin.PropertyEditing/ViewModels/PropertyGroupViewModel.cs
Fixes #525
When we moved to the new panel group system, the grouped editors weren't
accounted for and so when we try to remove their child property from the
container group it's not found since they're inside the group editor VM.
This also meant that even if removal had worked, we wouldn't properly
add new shared view model types to the group.
> Grouped type fixes

- Xamarin.PropertyEditing.Tests/PanelViewModelTests.cs
- Xamarin.PropertyEditing/ViewModels/PanelViewModel.cs
- Xamarin.PropertyEditing/ViewModels/PropertyGroupViewModel.cs
Fixes #525
When we moved to the new panel group system, the grouped editors weren't
accounted for and so when we try to remove their child property from the
container group it's not found since they're inside the group editor VM.
This also meant that even if removal had worked, we wouldn't properly
add new shared view model types to the group.
This version addresses the crasher listed in #527, the second issue was a false alarm.
> [Core] Fix grouped type properties not swapping properly

- Xamarin.PropertyEditing.Mac/Controls/FilePathEditorControl.cs
Essentially `StoreCurrentValue()` did an invalid null check, which was stopping the new value being re-set.
> [Mac] Fix reveal not enabling

- Xamarin.PropertyEditing.Mac/Controls/CombinablePropertyEditor.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/BrushTabViewController.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/PropertyButton.cs
- Xamarin.PropertyEditing.Mac/Controls/EditorContainer.cs
- Xamarin.PropertyEditing.Mac/Controls/NumericEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/ObjectEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/PropertyEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/StringEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/TypeSelectorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/TypeSelectorWindow.cs
- Xamarin.PropertyEditing.Mac/PropertyEditorPanel.cs
- Xamarin.PropertyEditing.Mac/PropertyEditorSelector.cs
- Xamarin.PropertyEditing.Mac/PropertyTableDataSource.cs
- Xamarin.PropertyEditing.Mac/PropertyTableDelegate.cs
- Xamarin.PropertyEditing.Mac/Xamarin.PropertyEditing.Mac.csproj
- Xamarin.PropertyEditing.Tests/ObjectPropertyViewModelTests.cs
- Xamarin.PropertyEditing/Extensions.cs
- Xamarin.PropertyEditing/Properties/Resources.Designer.cs
- Xamarin.PropertyEditing/Properties/Resources.resx
- Xamarin.PropertyEditing/ViewModels/ObjectPropertyViewModel.cs
- Xamarin.PropertyEditing/ViewModels/TypeSelectorViewModel.cs
This PR:
- Adds the object editor control for Mac (closes #141)
- Reimplements the disclosure handling for the outline view allowing us to properly control backgrounds
- Adds a reusable type selector which is needed for the both this editor and the binding editor
- Fixes reuse for first instance of each editor type (first-sized)
> Mac object editor

- Xamarin.PropertyEditing.Mac/Controls/BasePointEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/BaseRectangleEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/BrushEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/NumericSpinEditor.cs
- Xamarin.PropertyEditing.Mac/Controls/NumericEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/PointEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/PredefinedValuesEditor.cs
- Xamarin.PropertyEditing.Mac/Controls/PropertyEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/RatioEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/RectangleEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/SizeEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/ThicknessEditorControl.cs
- Xamarin.PropertyEditing.Mac/PropertyTableDelegate.cs
Controls resized as per control width
Supposed to fix this - https://github.com/xamarin/Xamarin.PropertyEditing/issues/518
Narrow:
Wide:
> Resize Point and Rectangle controls based on overall width.

- Xamarin.PropertyEditing.Mac/Controls/ControlExtensions.cs
- Xamarin.PropertyEditing.Mac/Controls/ObjectEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/TypeEditorControl.cs
- Xamarin.PropertyEditing.Mac/PropertyEditorSelector.cs
- Xamarin.PropertyEditing.Mac/Xamarin.PropertyEditing.Mac.csproj
- Xamarin.PropertyEditing.Tests/MockControls/MockControl.cs
- Xamarin.PropertyEditing.Tests/MockControls/MockSampleControl.cs
- Xamarin.PropertyEditing.Tests/MockPropertyInfo/MockPropertyInfo.cs
- Xamarin.PropertyEditing.Windows/EditorPropertySelector.cs
- Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
- Xamarin.PropertyEditing.Windows/TypeEditorControl.cs
- Xamarin.PropertyEditing.Windows/Xamarin.PropertyEditing.Windows.csproj
- Xamarin.PropertyEditing/Properties/Resources.Designer.cs
- Xamarin.PropertyEditing/Properties/Resources.resx
- Xamarin.PropertyEditing/Reflection/ReflectionObjectEditor.cs
- Xamarin.PropertyEditing/ViewModels/PropertiesViewModel.cs
- Xamarin.PropertyEditing/ViewModels/TypePropertyViewModel.cs
- Xamarin.PropertyEditing/Xamarin.PropertyEditing.csproj
This introduces a `ITypeInfo` based property editor for Windows and Mac that reuses the object editor setup, but only selects types. Implementers will need to watch for the property in `GetAssignableTypes` and return an appropriate set of types for that property.
> Type selector editor

- Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
Bind the automation property name for the CollectionEditor launch button to the name of the PropertyEditorControl to satisfy MAS 4.1.2. Siblings are required to have unique names, unless they have a different `LocalizedControlType`
> Fix 755236

- Xamarin.PropertyEditing.Tests/ObjectPropertyViewModelTests.cs
- Xamarin.PropertyEditing.Tests/SimpleCollectionViewTests.cs
- Xamarin.PropertyEditing/ViewModels/ObjectPropertyViewModel.cs
- Xamarin.PropertyEditing/ViewModels/SimpleCollectionView.cs
- Fixes a crasher if you canceled type selection in windows (behavior changed when mac changed it to an async)
- Fixes "Show all assemblies includes blank categories" #522
> Object editor / type selector fixes

- Xamarin.PropertyEditing.Mac/Controls/RequestResource/RequestResourceView.cs
Originally it was trying to use the ResourceSelector property from BrushPropertyViewModel
but that's intended for a resource request, it's for the inline resource selector. In
trying to do this it didn't do proper null checks for the property, so it'd crash when
it inevitably wasn't found.
> [mac] Fix resource selection on non-brushes

- Xamarin.PropertyEditing.Mac/PropertyEditorPanel.cs
The resources are consumed in Initialize, which is called by the constructors, so we need a way to set it as part of construction.
> [Mac] Introduce a version of the mac control where the host resource provider can be passed into the constructor

- Xamarin.PropertyEditing.Mac/PropertyList.cs
Fixes - https://github.com/xamarin/Xamarin.PropertyEditing/issues/510
If the outline view is made the first responder we should select
the first row (if there's no selection) and then we should make
it the first responder.
> [Mac] Handle tabbing into the NSOutlineView

- Xamarin.PropertyEditing.Mac/Controls/Custom/CommonBrushLayer.cs
The vertical margin was being added every time the control was being redrawn.
> Fixes shrinking color rectangles in the color swatch selector.

- Xamarin.PropertyEditing.Mac/Controls/Custom/MaterialView.cs
I'm not totally confident I used the API correctly, though. Here's some screenshots.
> Adds tooltips for color swatches on mac

- Xamarin.PropertyEditing.Mac/Controls/RatioEditorControl.cs
- Xamarin.PropertyEditing.Mac/Extensions.cs
The simplest solution would have been to set Formatter property to null, but that blows up :/
So Marius has raised an issue for that on the Mac side here:
https://github.com/xamarin/xamarin-macios/issues/6032
and suggested this workaround
https://gist.github.com/Therzok/f735948ec766d2dca16af958913eef36
Which appears to work.
Fixes #553
> [Mac] Setting the Formatter by default breaks the RatioEditor rendering.

- Xamarin.PropertyEditing.Mac/Controls/EditorContainer.cs
Therefore the PropertyButton would not have been created.
This check stops a possible NRE.
> [Mac] NeedsPropertyButton maybe false when the EditorViewModel is set.

- Xamarin.PropertyEditing.Mac/Controls/PropertyContainer.cs
Fixes https://github.com/xamarin/Xamarin.PropertyEditing/issues/486
No Jiggery Pokery required.
> [Mac] Fix so that Property Labels truncate to a centre ellipsis.

- Xamarin.PropertyEditing.Windows/EditorPropertySelector.cs
This PR fixes `DateTime` editor for windows.
Regression from https://github.com/xamarin/Xamarin.PropertyEditing/pull/480
**Before**
**After**
> [Windows ] fix controls for DateTime and TimeSpan types

- Xamarin.PropertyEditing.Mac/Controls/Custom/AutoClosePopOver.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/BasePopOverControl.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/PropertyButton.cs
The popovers had their appearance set later, but weren't updating their
vibrant appearance so they were using the light appearance still.
Fixes #604
> [mac] Fix timing of appearance changes for popovers

- Xamarin.PropertyEditing.Mac/PropertyTableDataSource.cs
- Xamarin.PropertyEditing.Mac/PropertyTableDelegate.cs
Fixes an issue where reused open/collapse buttons would sometimes have the wrong visual state. Fixes #610
> Fix incorrect expansion after reuse

- Xamarin.PropertyEditing.Mac.Standalone/Main.storyboard
- Xamarin.PropertyEditing.Mac/PropertyEditorPanel.cs
The view adding the panel as a subview should control how it's sized,
not the panel itself.
> [mac] Don't autosize the editor panel

- Xamarin.PropertyEditing.Mac/Controls/Custom/BrushTabViewController.cs
Seems like we might be getting chang events even when not visible so let's ignore them
if we don't actually have a resource selector. The search box gets added regardless to
simplify putting it at the end.
> [mac] Ignore change events if no resources

- Xamarin.PropertyEditing/ViewModels/PredefinedValuesViewModel.cs
This removes a seeming requirement that the default value of a
predefiend values constrained property be the default of the type.
A object editor that properly supports default will return a default
value that is in the list of predefined values. Resetting the value does
not attempt to use the default value and instead simply passes Unset, so
there's no need for the default value to need to be known.
> [Core] Don't assume default is default(TValue)

- Xamarin.PropertyEditing.Tests/BrushPropertyViewModelTests.cs
- Xamarin.PropertyEditing.Tests/MockControls/MockResourceProvider.cs
- Xamarin.PropertyEditing/IResourceProvider.cs
- Xamarin.PropertyEditing/ViewModels/ResourceSelectorViewModel.cs
While most resource UIs have a popup or window that doesn't really
require a live refresh, the brush resource tab does have a persistent
list so it needs to be able to update. Since the view model is shared,
we get the former for free anyway.
> [Core] Support refreshing resources

- Xamarin.PropertyEditing.Mac/Controls/Custom/BrushTabViewController.cs
- Xamarin.PropertyEditing.Tests/MockControls/MockSampleControl.cs
- Xamarin.PropertyEditing/ViewModels/BrushPropertyViewModel.cs
Fixes some issues around reusing the brush tabbed view between properties that do and don't support resources.
> Fix resource/no resource brush swapping

- Xamarin.PropertyEditing.Mac/Controls/PropertyContainer.cs
> [Mac] Fix Scroll bar overlapping the Property Button.

- Xamarin.PropertyEditing.Mac/Controls/CustomExpressionView.cs
This prevents editorControl from ever being null
> [Mac] CustomExpressionView always set editorControl

- Xamarin.PropertyEditing.Mac/Controls/CollectionInlineEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/FocusablePopupButton.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/PropertyTextField.cs
- Xamarin.PropertyEditing.Mac/Controls/NumericEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/ObjectEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/PropertyEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/StringEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/TypeEditorControl.cs
- Xamarin.PropertyEditing.Mac/PropertyEditorPanel.cs
- Xamarin.PropertyEditing/Properties/Resources.Designer.cs
- Xamarin.PropertyEditing/Properties/Resources.resx
Before:
Fixes - https://github.com/xamarin/Xamarin.PropertyEditing/issues/667
Fixes - https://github.com/xamarin/Xamarin.PropertyEditing/issues/625
After:
> [Mac] Tweaks for a more consistent UX

- Xamarin.PropertyEditing.Tests/MockControls/MockSampleControl.cs
- Xamarin.PropertyEditing.Windows/CombinablePredefinedValuesEditorControl.cs
Windows has the surprising behavior that when an automation group (like a group of combinable checkboxes) has a colon in the name, the group label is not read by the narrator. This causes a problem for the Android designer, which has property names like "app:layout_anchorGravity". We work around this by replacing the colon with a space in the group's automation name.
> Fix a11y bug 999307

- Xamarin.PropertyEditing.Mac/Controls/EditorContainer.cs
- Xamarin.PropertyEditing.Mac/PropertyTableDelegate.cs
This method seems far more reliable for noticing when rows are removed so we can use it instead of changing to null superview (which sometimes it doesn't do). This fixes 966531.
> [mac] Use more reliable row removed notice

- Xamarin.PropertyEditing.Windows/CollectionEditorWindow.xaml.cs
Context [AB#1009752](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1009752)
Component initialization call before adding `MergedDictionaries`. Because `InitializeComponent` sets resources from the xaml file.
https://recordit.co/vQ846hHnp2
| Before| After |
|:----------:|:-------------:|
| ![Screenshot_2](https://user-images.githubusercontent.com/27482193/70074186-4073be80-160b-11ea-99bb-cabe7125830a.png) |  ![Screenshot_1](https://user-images.githubusercontent.com/27482193/70074184-4073be80-160b-11ea-9b9d-4411d516784e.png) |
> [win] fixes collection editor window

- Xamarin.PropertyEditing.Mac/Controls/TypeSelectorControl.cs
- Xamarin.PropertyEditing/Properties/Resources.Designer.cs
- Xamarin.PropertyEditing/Properties/Resources.resx
Fixes #688 
And https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1032219
As well as this field, we also need the localisation team to also localise the `PropertyFilterLabel` resource as that seems to have been missed across all, if not most languages.
> [Mac] Add missing placeholder resource for type filtering.

- Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
This fixes AB#1003978
Previously the choice buttons (used for picking brush type) showed focus via a different background color. But that color difference wasn't sufficiently obvious, per a11y testing, especially in the blue theme. Our UI designer suggested that we should show a focus rect to fix this.
Old UI (blue theme; note that the 3rd button has the focus):
Updated UI (blue theme):
Updated UI (dark theme):
> [VS] Show focus via focus rect, not color, for choice buttons

- Xamarin.PropertyEditing.Mac/Controls/CategoryContainerControl.cs
- Xamarin.PropertyEditing.Mac/Controls/PropertyEditorControl.cs
- Xamarin.PropertyEditing.Mac/PropertyTableDelegate.cs
Backport of #706 
(cherry picked from commit 9f4f8f52a6fdae38a0cccb141745194fc6e10426)
> [d16-6][Mac] Tabbing to OutlineView

- Xamarin.PropertyEditing.Mac/CocoaHelpers.cs
- Xamarin.PropertyEditing.Mac/Controls/CollectionEditorWindow.cs
- Xamarin.PropertyEditing.Mac/Controls/CollectionInlineEditorControl.cs
This issue was hitting some problems. Use NSApplication.SharedApplication.RunModalForWindow (window) over a GTK application has very odd behaviours with our hacks. In this case, it sets null the current NSApplication.SharedApplciation.MainWindow, and that's the reason because the focused ring is not visible and not receiving the keyevents.
Additional to this, the IDE has a default behaviour of focus the Document selected when it gets the focus, and this behaviour it was executed after the Proppy call. That's because now we wait until SynchronizationContext to execute our proppy focus call.
The fix doesn't breaks the Standalone
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1002094
> Adds a new mechanism to open Modal dialogs over VS4Mac context

- Xamarin.PropertyEditing.Windows/Themes/PropertyEditorPanelStyle.xaml
Set AutomationProperty.Name on the "advanced properties" expander
control (with value "Advanced Properties") for a11y.
Fixes [AB#1214551](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1214551)
> Add Name a11y property to expander

- Xamarin.PropertyEditing.Windows/Themes/PropertyEditorPanelStyle.xaml
Hitting tab should never set focus to the property editor panel itself. Fixed [AB#1251446](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1251446)
> Don't allow property editor panel to get the focus

- Xamarin.PropertyEditing.Windows/Themes/PropertyEditorPanelStyle.xaml
Hitting tab should never set focus to the property editor panel itself. Fixed [AB#1251446](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1251446)
Backport of #763
> [d16-9] Don't allow property editor panel to get the focus

- Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
- Xamarin.PropertyEditing.Windows/Themes/VS.Dark.xaml
- Xamarin.PropertyEditing.Windows/Themes/VS.Light.xaml
Fix [AB#1251444](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1251444). The rule is that the border for edit boxes (and all controls) when focused must have at least a 3:1 contrast difference with the border when unfocused - there must enough contrast difference to make obvious to all that the visual state changed. That wasn't the case for our edit boxes before but is now. Updated to use the same themed border & text colors as the as the Cider colors, used by the WPF designer, which we've kept consistent with in the past.
Checkboxes and buttons already show a dashed outline for a focus rect. That's not the current standard for VS UI controls, but it's what it's always done and is fine from an a11y point of view, since there's even more obvious …
> Fix edit box focus border contrast

- Xamarin.PropertyEditing.Mac/PropertyList.cs
Fixes VSTS #1340425: Property pane has double chevrons
old
new
> Fixes double disclosure triangle in Property panel

- Xamarin.PropertyEditing.Mac/HostResourceProvider.cs
Fix [AB#1468252](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1468252)
Apparently there are scenarios where CurrentAppearance is not
set by the client on HostResourceProvider (UITools sets it but
vsmac doesn't currently) nor is NSAppearance.CurrentAppearance
set on the current thread (perhaps the thread is newly
created and AppKit didn't get a chance to set it), causing
bug 1468252.
To protect against that, we check if both are null and in that
case just assume it's light theme rather than generate an NRE.
> Protect against CurrentAppearance NRE

- Xamarin.PropertyEditing.Mac/HostResourceProvider.cs
Fix [AB#1468252](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1468252)
Apparently there are scenarios where CurrentAppearance is not
set by the client on HostResourceProvider (UITools sets it but
vsmac doesn't currently) nor is NSAppearance.CurrentAppearance
set on the current thread (perhaps the thread is newly
created and AppKit didn't get a chance to set it), causing
bug 1468252.
To protect against that, we check if both are null and in that
case just assume it's light theme rather than generate an NRE.
Backport of #789
> [d17-0-vsmac] Protect against CurrentAppearance NRE

- Xamarin.PropertyEditing.Mac/Controls/Custom/CommonBrushLayer.cs
- Xamarin.PropertyEditing.Mac/PropertyTableDelegate.cs
With the macos P13 API type changes, an issue was introduced since
casting an ObjCRuntime.nfloat to an nint (aka IntPtr) doesn't work
properly - (nint)(ObjCRuntime.nfloat)23 for instance will evaluate
to 0x4037000000000000, the floating point bits are just reinterpreted
as an int rather than actually being converted.
That in turn caused huge sizes for width and height causing
new CGBitmapContext to throw an exception.
Adding the double cast here fixes this, for now.
Soon ObjCRuntime.nfloat will go away, replaced by
System.Runtime.InteropServices.NFloat, but for now
this workaround makes us work.
Fixes:
[AB#1487089](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1487089)
[AB#1487070](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_ …
> Add cast to fix bug with numeric conversion

- Xamarin.PropertyEditing.Mac/Controls/Custom/CommonBrushLayer.cs
- Xamarin.PropertyEditing.Mac/PropertyTableDelegate.cs
With the macos P13 API type changes, an issue was introduced since
casting an ObjCRuntime.nfloat to an nint (aka IntPtr) doesn't work
properly - (nint)(ObjCRuntime.nfloat)23 for instance will evaluate
to 0x4037000000000000, the floating point bits are just reinterpreted
as an int rather than actually being converted.
That in turn caused huge sizes for width and height causing
new CGBitmapContext to throw an exception.
Adding the double cast here fixes this, for now.
Soon ObjCRuntime.nfloat will go away, replaced by
System.Runtime.InteropServices.NFloat, but for now
this workaround makes us work.
Fixes:
[AB#1487089](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1487089)
[AB#1487070](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_ …
> [main] Add cast to fix bug with numeric conversion

- Xamarin.PropertyEditing.Mac/Controls/BasePathEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/BasePointEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/BaseRectangleEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/BooleanEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/BrushEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/CharEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/CollectionInlineEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/CombinablePropertyEditor.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/FocusableBooleanButton.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/FocusableButton.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/FocusableComboBox.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/FocusablePopupButton.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/NumericSpinEditor.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/NumericTextField.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/ProxyResponderButton.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/TextFieldSmallButtonContainer.cs
- Xamarin.PropertyEditing.Mac/Controls/EntryPropertyEditor.cs
- Xamarin.PropertyEditing.Mac/Controls/NumericEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/PredefinedValuesEditor.cs
- Xamarin.PropertyEditing.Mac/Controls/PropertyEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/ProxyRowResponder.cs
- Xamarin.PropertyEditing.Mac/Controls/RatioEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/StringEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/TimeSpanEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/TypeEditorControl.cs
- Xamarin.PropertyEditing.Mac/PropertyList.cs
The old approach was doing a recusive iteration on every editor multiple times re-configuring next responder in any focus change, which was complicated to maintain/understand and dowhile{} was giving us unexpected results (Infinite loops).
To try improve how focus is handled over this views, now we only calculate the next/previous responder "on demand", when tab or shift+tab is pressed in a specific view implementing a ProxyRowResponder which knows if is first/end view and moves to the next available editor.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1472832
> Reimplementation UpdateKeyViews() based in ProxyRowResponder

- Xamarin.PropertyEditing.Mac/Controls/BasePathEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/BasePointEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/BaseRectangleEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/BooleanEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/BrushEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/CharEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/CollectionInlineEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/CombinablePropertyEditor.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/FocusableBooleanButton.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/FocusableButton.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/FocusableComboBox.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/FocusablePopupButton.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/NumericSpinEditor.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/NumericTextField.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/ProxyResponderButton.cs
- Xamarin.PropertyEditing.Mac/Controls/Custom/TextFieldSmallButtonContainer.cs
- Xamarin.PropertyEditing.Mac/Controls/EntryPropertyEditor.cs
- Xamarin.PropertyEditing.Mac/Controls/NumericEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/PredefinedValuesEditor.cs
- Xamarin.PropertyEditing.Mac/Controls/PropertyEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/ProxyRowResponder.cs
- Xamarin.PropertyEditing.Mac/Controls/RatioEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/StringEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/TimeSpanEditorControl.cs
- Xamarin.PropertyEditing.Mac/Controls/TypeEditorControl.cs
- Xamarin.PropertyEditing.Mac/PropertyList.cs
The old approach was doing a recusive iteration on every editor multiple times re-configuring next responder in any focus change, which was complicated to maintain/understand and dowhile{} was giving us unexpected results (Infinite loops).
To try improve how focus is handled over this views, now we only calculate the next/previous responder "on demand", when tab or shift+tab is pressed in a specific view implementing a ProxyRowResponder which knows if is first/end view and moves to the next available editor.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1472832
Backport of #792
> [main] Reimplementation UpdateKeyViews() based in ProxyRowResponder

- Xamarin.PropertyEditing.Windows/Themes/PropertyEditorPanelStyle.xaml
Now hitting the Tab key in the last control in the property
editor changes focus to the search control at the top,
cycling around. And Shift-Tab in search moves to the
last control.
Fixes [AB#1491221](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1491221)
> Make tab order cycle for proppy controls

- Xamarin.PropertyEditing.Windows/Themes/PropertyEditorPanelStyle.xaml
- Xamarin.PropertyEditing/Properties/Resources.resx
The name here should generally match the button label -
it's a name, not a description.
Fixes [AB#1491218](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1491218)
> Set the Arrange By AutomationProperty Name correctly

- Directory.Build.targets
When MicroBuild signing is enabled, the SignFiles task will run every time a project is built, even if it's already been compiled once before. In this scenario, the dlls have already been created and signed once (in the initial build), so MSBuild will skip the compilation step, but SignFiles will run again and unnecessarily submit the already-signed dlls for signing again. Since signing can be quite expensive, this redundant signing adds a significant amount of time to builds.
To prevent it from happening, we can *disable* signing at the start of the build, then only re-enable it if Compile runs. If Compile is skipped, signing will remain disabled, and we will not sign anything unnecessarily.
I've validated this works through builds in the UITools pipeline, i.e. …
> Reduce Redundant MicroBuild Signing

- Xamarin.PropertyEditing.Windows/PropertyPresenter.cs
- Xamarin.PropertyEditing.Windows/Themes/Resources.xaml
Ctrl+Space is the keyboard short that can
be used to show the property editor menu
for a property (with options like Reset,
Convert to Local Value, etc.). Previously, that
was detected via a KeyBinding in XAML, which
worked for text boxes but not controls like
checkbox and button, which handle the
key down event themselves. Now we
use PreviewKeyDown instead, handling that
in C# code, to work for all control
types.
Fixes [AB#1491229](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1491229)
> Use PreviewKeyDown for Ctrl+Space to show menu

- Xamarin.PropertyEditing.Windows/BrushEditorControl.cs
Fixes:
[Bug 1491842](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1491842): A11y_The brush icons popups which is present for options like background brush is not getting closed when pressing esc key_XamarinDevelopment_AddUI_Keyboard
When focus is in the brush editor popup, hitting the ESC key would set focus back to the active document tab, and leave the popup open.
This change adds the proper ESC key handler and blocks VS from uses the accelerator for ESC (which focuses the active document)
> Allow ESC key to close brush editor popup

- Xamarin.PropertyEditing.Windows/ComboBoxEx.cs
Set the Automation.Name property for the TextEdit control in
an editable combo to be the same as that for the entire combo
box.
Fixes [AB#1501925](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1501925)
> Set a11y name for editable combo TextEdit

- .build/automation/stages/validate.yml
- Directory.Build.props
- Directory.Build.targets
- Xamarin.PropertyEditing/Xamarin.PropertyEditing.csproj
With the move away from the "sign-from-github-esrp" ("Groovy") pipeline, we need to shift our assembly signing to happen alongside the build itself, which is more secure. Without these changes, we will not be able to push new, signed assemblies from this branch.
**Important Note:** This change also disables Mac build & validation. These stages are currently broken with or without the signing changes, but since d17-1 should only be used to ship windows builds, they're superfluous anyway and I believe they can just be turned off (we did the same in d17-0)...
> Port MicroBuild Signing to d17 1

- Xamarin.PropertyEditing.Windows.Standalone/Xamarin.PropertyEditing.Windows.Standalone.csproj
- Xamarin.PropertyEditing.Windows/Xamarin.PropertyEditing.Windows.csproj
Trying to clean the vulnerability for system.net.http 4.1.0. Removing any unused reference in property inspector before merging the submodule into UI tools
> Remove system.net.http unused reference

- Xamarin.PropertyEditing.Mac/PropertyList.cs
Remove the call to UpdateExpansions after ReloadData in response to
OnPropertiesChanged (e.g. called when selection changes). This
doesn't seem necessary, as when views are recreated their
expansion status is set correctly originally and AppKit
remembers expansion state after.
Further, this fixes [AB#1521131](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1521131), where the Name and Type rows are
sometimes blank - apparently expanding manually, and doing it
synchronously like that, causes the NSOutlineView
to get confused and not show the top row sometimes.
> Remove UpdateExpansions

- Xamarin.PropertyEditing.Mac/PropertyList.cs
Remove the call to UpdateExpansions after ReloadData in response to
OnPropertiesChanged (e.g. called when selection changes). This
doesn't seem necessary, as when views are recreated their
expansion status is set correctly originally and AppKit
remembers expansion state after.
Further, this fixes [AB#1521131](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1521131), where the Name and Type rows are
sometimes blank - apparently expanding manually, and doing it
synchronously like that, causes the NSOutlineView
to get confused and not show the top row sometimes.
Backport of #812
> [main] Remove UpdateExpansions

- bot-provisioning/dependencies.csx
Fixes this error that some people are seeing:
> Workload installation failed: microsoft.net.runtime.monoaotcompiler.task::6.0.4 is not found in NuGet feeds https://aka.ms/dotnet6/nuget/index.json;https://devdiv.pkgs.visualstudio.com/DevDiv/_packaging/VSMac/nuget/v3/index.json".
See xamarin/provisionator#455
> Update macos workload provisioning

- Xamarin.PropertyEditing.Mac/Controls/Custom/HistoryLayer.cs
Fix [AB#1569130](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1569130)
Due to the issue https://github.com/xamarin/xamarin-macios/issues/15600, when a CGColor is allocated and its native object about to be passed to PInvoke when setting CALayout.BackgroundColor, it's possible for it be GC'ed, which CFReleases the CGColor, before the PInvoke completes and BackgroundColor gets a chance to CFRetain it. In that case, the BackgroundColor can point to a deleted object. Until there's a real fix for that race condition with https://github.com/xamarin/xamarin-macios/issues/15600 fixed, we workaround it here by doing a GC.KeepAlive ensuring that the object lives until the PInvoke completes.
Also, in some scenarios looks like ViewModel is not yet set in …
> [HistoryLayer] On viewmodel changes we ensure our viewmodel is not null and set default color

- Xamarin.PropertyEditing.Mac/Controls/PanelHeaderEditorControl.cs
- Xamarin.PropertyEditing.Mac/PropertyTableDelegate.cs
The Name field should only show in the property UI if the object is nameable - which it normally isn’t. The Name UI is properly hidden on VS Windows - it
just wasn’t on Mac. That’s fixed now.
Fixes AB#1615257
UI with fix:
Original UI:
> Hide Name UI unless object is nameable

- Xamarin.PropertyEditing/ViewModels/PredefinedValuesViewModel.cs
If a predefined property value is set that doesn't match one of the standard options, then set it as the valueName, same as if it was passed in the ValueDescriptor. This fixes showing the custom value in the property editor UI. Fixes AB#1600201.
Proppy's intention may have been that custom values like this should be set in the ValueDescriptor instead of Value - I'm not sure about that. However the Forms XAML code doesn't do that. Given that, and the fact that there's no harm is allowing custom values to be specified in the Value instead of just ValueDescriptor, we now support both.
> Fix setting custom values for non-constrained enums

- Xamarin.PropertyEditing.Mac/Controls/EditorContainer.cs
- Xamarin.PropertyEditing.Mac/PropertyList.cs
- Xamarin.PropertyEditing.Mac/PropertyTableDelegate.cs
Fix so that when a category is expanded by default the UI shows the proper icon (the expanded icon, not collapsed).
There are two main changes here:
1. Remove the code added in https://github.com/xamarin/Xamarin.PropertyEditing/commit/96561f19bf1c81e24c852e0a88ef46bd72e05e38 to support custom disclosures for Catalina. That's no longer required in newer versions of macOS. Now we just let AppKit handle setting the right disclosure icon.
2. Add call to UpdateExpansions in OnPropertiesChanged, so that the default expansion state is correct when the property editor context changes, ensuring that categories are autoexpanded when they are supposed to be.
Fixes AB#1559942
> Show proper expanded icon by default

- NuGet.Config
When using the latest internal .NET SDK the build will fail since Xamarin.PropertyEditing cannot resolve the latest packages since all internal package sources are cleared. Resulting in a build failure:
error NU1102: Unable to find package Microsoft.NETCore.App.Ref with version (= 6.0.14)
Backport of https://github.com/xamarin/Xamarin.PropertyEditing/pull/828
> Allow other NuGet feeds when building

- Xamarin.PropertyEditing.Mac/MacSystemInformation.cs
- Xamarin.PropertyEditing.Mac/PropertyList.cs
NSTableView.FullWidth is only explicitly supported on Big Sur and later, so don't set it for older versions of macOS. For older versions of macOS, FullWidth is apparently the default so doesn't need to be specified.
This updates the layout UI tweaks included in
https://github.com/xamarin/Xamarin.PropertyEditing/pull/817.
Fixes AB#1776438
> Fix API not supported on Catalina

- Xamarin.PropertyEditing.Mac/MacSystemInformation.cs
- Xamarin.PropertyEditing.Mac/PropertyList.cs
NSTableView.FullWidth is only explicitly supported on Big Sur and later, so don't set it for older versions of macOS. For older versions of macOS, FullWidth is apparently the default so doesn't need to be specified.
This updates the layout UI tweaks included in
https://github.com/xamarin/Xamarin.PropertyEditing/pull/817.
Fixes AB#1776438
Backport of #830
> [d17-6] Fix API not supported on Catalina

- .build/automation/stages/validate.yml
- NuGet.Config
For compliance we can't use the default public NuGet feed.
Instead, use the same feeds (some of them) that are used for xamarin-android (https://github.com/xamarin/xamarin-android/blob/main/NuGet.config), another public repo.
Also disable building for Mac, since it's no longer needed.
> Update AzDO NuGet feed, as required for compliance

- .build/automation/stages/localization-handback.yml
- .build/automation/stages/localization-handoff.yml
- .build/automation/variables.yml
Use the `OneLocBuild--PAT` provided by the `Xamarin-Secrets` variable group instead of the `OneLocBuildPAT` variable defined on the build definition. This will make PAT rotations more reliable going forward
> Localization Handoff: Use keyvault-backed nuget feed access PAT

- .github/workflows/backport-trigger.yml
- .github/workflows/localization-pr.yml
- .github/workflows/rebase-trigger.yml
Provide permission block to allow GITHUB_TOKEN access to continue working after 2024-02-01
Guidance: https://docs.opensource.microsoft.com/github/apps/permission-changes/
> GITHUB_TOKEN read-only change: Include permissions block

- .build/automation/stages/localization-handback.yml
- .build/automation/stages/localization-handoff.yml
- .build/automation/variables.yml
Related work item: VS #[2053237](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2053237)
Obtain a OneLocBuild feed access token via the `VSEng-AzureDevOps-ceapex-OneLocBuild` service connection
Removes the dependency on the `OneLocBuild--PAT` static token
GitHub.Token did not seem to be defined and so added it to variables
> Generate token for use by the OneLocBuild task

- .github/workflows/rebase-trigger.yml
VS #[2172843](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2172843)
Remove dependency on Azure DevOps personal access token (PAT) registration represented by the ADO_BUILDPAT setting.  Instead use a managed identity (MI) represented by the REBASE_ settings as a means of authorizing with Azure DevOps
> Rebase bot: Use managed identity (MI) authorization
